// ─── Inventory — Data Types, Categories & Mock Data ─────────────────────────

export type StockStatus = 'In Stock' | 'Low Stock' | 'Out of Stock';
export type Category    = string;

// ─── Sub-category definition ──────────────────────────────────────────────────
export interface SubCategory {
  id: string;
  label: string;
  category: Category;
  icon: string;                   // Material Symbol fallback icon
  image: string;                  // representative image URL
  description?: string;
}

// ─── Product ──────────────────────────────────────────────────────────────────
export interface Product {
  id: number;
  sku: string;
  name: string;
  category: Category;
  subCategory: string;            // matches SubCategory.id
  brand: string;
  unit: string;
  purchasePrice: number;
  sellingPrice: number;
  wholesalePrice: number;
  gst: number;
  stock: number;
  minStock: number;
  maxStock: number;
  warehouse: string;
  rack: string;
  barcode: string;
  status: StockStatus;
  image?: string;                 // product image URL
}

// ─── All sub-categories grouped by main category ──────────────────────────────
export const SUBCATEGORIES: SubCategory[] = [

  // ── Plumbing ──────────────────────────────────────────────────────────────
  { id: 'plumbing-pipes',    label: 'Pipes',          category: 'Plumbing',   icon: 'settings_input_component', image: 'assets/inventory/subcategories/plumbing-pipes.png',    description: 'PVC, GI, CPVC pipes' },
  { id: 'plumbing-fittings', label: 'Fittings',       category: 'Plumbing',   icon: 'device_hub',               image: 'assets/inventory/subcategories/plumbing-fittings.png', description: 'Elbows, tees, couplings' },
  { id: 'plumbing-valves',   label: 'Valves',         category: 'Plumbing',   icon: 'turn_right',               image: 'assets/inventory/subcategories/plumbing-valves.png',   description: 'Ball valves, gate valves' },
  { id: 'plumbing-traps',    label: 'Traps & Drains', category: 'Plumbing',   icon: 'water_drop',               image: 'assets/inventory/subcategories/plumbing-traps.png',    description: 'P-traps, floor traps' },

  // ── Electrical ────────────────────────────────────────────────────────────
  { id: 'elec-switches',      label: 'Switches & Sockets',           category: 'Electrical', icon: 'toggle_on',             image: 'assets/inventory/subcategories/elec-switches.png',      description: '6A/16A switches, sockets, dimmers, regulators' },
  { id: 'elec-wires',         label: 'Wires & Cables',               category: 'Electrical', icon: 'cable',                 image: 'assets/inventory/subcategories/elec-wires.png',         description: 'Single-core, flexible, coaxial, LAN cables' },
  { id: 'elec-mcb',           label: 'MCB & Switchgear',             category: 'Electrical', icon: 'electric_meter',        image: 'assets/inventory/subcategories/elec-mcb.png',           description: 'MCB, RCCB, RCBO, isolators, contactors' },
  { id: 'elec-conduit',       label: 'Conduit & Fittings',           category: 'Electrical', icon: 'cylinder',              image: 'assets/inventory/subcategories/elec-conduit.png',       description: 'PVC conduit, bends, tees, junction boxes' },
  { id: 'elec-lighting',      label: 'Lighting',                     category: 'Electrical', icon: 'light',                 image: 'assets/inventory/subcategories/elec-lighting.png',      description: 'LED bulbs, tubes, panels, floodlights' },
  { id: 'elec-accessories',   label: 'Power Accessories',            category: 'Electrical', icon: 'power',                 image: 'assets/inventory/subcategories/elec-accessories.png',   description: 'Extension boards, adaptors, connectors, terminals' },
  { id: 'elec-fans',          label: 'Fans & Controls',              category: 'Electrical', icon: 'mode_fan',              image: 'assets/inventory/subcategories/elec-fans.png',          description: 'Ceiling, exhaust, wall fans & capacitors' },
  { id: 'elec-doorbell',      label: 'Doorbell & Security',          category: 'Electrical', icon: 'notifications_active',  image: 'assets/inventory/subcategories/elec-doorbell.png',      description: 'Bells, doorbells, sensors, indicators' },
  { id: 'elec-installation',  label: 'Installation Accessories',     category: 'Electrical', icon: 'electrical_services',   image: 'assets/inventory/subcategories/elec-installation.png',  description: 'Boxes, holders, clips, earthing, terminals' },
  { id: 'elec-tools',         label: 'Tools',                        category: 'Electrical', icon: 'hardware',              image: 'assets/inventory/subcategories/elec-tools.png',         description: 'Testers, pliers, strippers, crimpers' },
  { id: 'elec-appliances',    label: 'Appliances & Power',           category: 'Electrical', icon: 'home_appliances',       image: 'assets/inventory/subcategories/elec-appliances.png',    description: 'Inverter, UPS, stabilizer, immersion rod' },

  // ── Hardware ──────────────────────────────────────────────────────────────
  { id: 'hw-fasteners',      label: 'Fasteners & Bolts',  category: 'Hardware',   icon: 'settings',      image: 'assets/inventory/subcategories/hw-fasteners.png',      description: 'Bolts, nuts, screws, anchors' },
  { id: 'hw-welding',        label: 'Welding',            category: 'Hardware',   icon: 'local_fire_department', image: 'assets/inventory/subcategories/hw-welding.png', description: 'Welding rods, electrodes' },
  { id: 'hw-tools',          label: 'Hand Tools',         category: 'Hardware',   icon: 'hardware',      image: 'assets/inventory/subcategories/hw-tools.png',          description: 'Drill bits, spanners, hammers' },

  // ── Agriculture ───────────────────────────────────────────────────────────
  { id: 'agr-seeds',       label: 'Seeds & Planting Material', category: 'Agriculture', icon: 'grass',        image: 'assets/inventory/subcategories/agr-seeds.png',      description: 'Wheat, rice, vegetable & fodder seeds' },
  { id: 'agr-fertilizers', label: 'Fertilizers & Manure',      category: 'Agriculture', icon: 'compost',      image: 'assets/inventory/subcategories/agr-fertilizers.png', description: 'Urea, DAP, NPK, organic & bio-fertilizers' },
  { id: 'agr-pesticides',  label: 'Pesticides & Crop Protection', category: 'Agriculture', icon: 'bug_report', image: 'assets/inventory/subcategories/agr-pesticides.png',  description: 'Insecticides, fungicides, herbicides, neem oil' },
  // { id: 'agr-irrigation',  label: 'Irrigation',                category: 'Agriculture', icon: 'water',        image: 'assets/inventory/subcategories/agr-irrigation.png',  description: 'Drip tubes, sprinklers, pipes' },
  // { id: 'agr-covering',    label: 'Shade & Covering',          category: 'Agriculture', icon: 'wb_shade',     image: 'assets/inventory/subcategories/agr-covering.png',    description: 'Shade nets, tarpaulins, mulch film' },

  // ── Paint ─────────────────────────────────────────────────────────────────
  { id: 'paint-interior',    label: 'Interior Wall Paints',        category: 'Paint', icon: 'format_paint',   image: 'assets/inventory/subcategories/paint-interior.png',   description: 'Emulsion, distemper, matte, satin, silk finish' },
  { id: 'paint-exterior',    label: 'Exterior Wall Paints',        category: 'Paint', icon: 'house',          image: 'assets/inventory/subcategories/paint-exterior.png',   description: 'Weatherproof, weather coat, acrylic exterior' },
  { id: 'paint-primer',      label: 'Primers & Sealers',           category: 'Paint', icon: 'layers',         image: 'assets/inventory/subcategories/paint-primer.png',     description: 'Wall primer, metal primer, wood primer, epoxy primer' },
  { id: 'paint-putty',       label: 'Wall Putty & Fillers',        category: 'Paint', icon: 'texture',        image: 'assets/inventory/subcategories/paint-putty.png',      description: 'White cement putty, acrylic putty, crack filler' },
  { id: 'paint-wood',        label: 'Wood Paint & Coatings',       category: 'Paint', icon: 'park',           image: 'assets/inventory/subcategories/paint-wood.png',       description: 'Wood primer, enamel, polish, PU coating, stain' },
  { id: 'paint-metal',       label: 'Metal Paint & Coatings',      category: 'Paint', icon: 'construction',   image: 'assets/inventory/subcategories/paint-metal.png',      description: 'Red oxide, enamel, anti-rust, aluminium paint' },
  { id: 'paint-enamel',      label: 'Enamel Paints',               category: 'Paint', icon: 'palette',        image: 'assets/inventory/subcategories/paint-enamel.png',     description: 'Synthetic enamel, gloss, semi-gloss, quick dry' },
  { id: 'paint-waterproof',  label: 'Waterproofing',               category: 'Paint', icon: 'water_damage',   image: 'assets/inventory/subcategories/paint-waterproof.png', description: 'Terrace, roof, bathroom, damp proof coatings' },
  { id: 'paint-texture',     label: 'Texture & Decorative',        category: 'Paint', icon: 'grain',          image: 'assets/inventory/subcategories/paint-texture.png',    description: 'Wall texture, sand, stone, metallic, marble finish' },
  { id: 'paint-floor',       label: 'Floor Paint & Coatings',      category: 'Paint', icon: 'grid_on',        image: 'assets/inventory/subcategories/paint-floor.png',      description: 'Epoxy, PU floor coating, anti-skid, road marking' },
  { id: 'paint-thinner',     label: 'Thinners & Solvents',         category: 'Paint', icon: 'science',        image: 'assets/inventory/subcategories/paint-thinner.png',    description: 'Paint thinner, PU thinner, turpentine, brush cleaner' },
  { id: 'paint-additive',    label: 'Hardeners & Additives',       category: 'Paint', icon: 'colorize',       image: 'assets/inventory/subcategories/paint-additive.png',   description: 'PU hardener, epoxy hardener, tinting paste, colourants' },
  { id: 'paint-brush',       label: 'Brushes & Rollers',           category: 'Paint', icon: 'brush',          image: 'assets/inventory/subcategories/paint-brush.png',      description: 'Flat, wall, enamel brushes; foam, microfiber rollers' },
  { id: 'paint-tools',       label: 'Painting Tools & Accessories',category: 'Paint', icon: 'handyman',       image: 'assets/inventory/subcategories/paint-tools.png',      description: 'Paint tray, scraper, masking tape, sandpaper, sealants' },

 ];

// Helper: get subcategories for a given category
export function getSubCategories(category: string): SubCategory[] {
  return SUBCATEGORIES.filter(s => s.category === category);
}

// ─── Categories sidebar list ──────────────────────────────────────────────────
export const CATEGORIES: { id: string; label: string; icon: string; count: number; image: string }[] = [
  // { id: 'all',         label: 'All Products', icon: 'apps',              count: 20, image: 'assets/inventory/categories/all.png' },
  { id: 'plumbing',    label: 'Plumbing',     icon: 'plumbing',          count: 5,  image: 'assets/inventory/categories/plumbing.png' },
  { id: 'electrical',  label: 'Electrical',   icon: 'bolt',              count: 81, image: 'assets/inventory/categories/electrical.png' },
  { id: 'hardware',    label: 'Hardware',     icon: 'hardware',          count: 3,  image: 'assets/inventory/categories/hardware.png' },
  { id: 'agriculture', label: 'Agriculture',  icon: 'grass',             count: 40, image: 'assets/inventory/categories/agriculture.png' },
  { id: 'paint',       label: 'Paint',        icon: 'format_paint',      count: 92, image: 'assets/inventory/categories/paint.png' },
 ];

// ─── Products with subCategory and image ─────────────────────────────────────
export const PRODUCTS: Product[] = [
  // ── Electrical → Switches & Sockets
  { id: 6,   sku: 'ELE-SW-001', name: '6A Switch',              category: 'Electrical', subCategory: 'elec-switches',     brand: 'Anchor',   unit: 'Piece', purchasePrice: 18,   sellingPrice: 28,   wholesalePrice: 22,  gst: 18, stock: 150, minStock: 50,  maxStock: 500,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560101', status: 'In Stock',   image: '' },
  { id: 7,   sku: 'ELE-SW-002', name: '16A Switch',             category: 'Electrical', subCategory: 'elec-switches',     brand: 'Anchor',   unit: 'Piece', purchasePrice: 25,   sellingPrice: 38,   wholesalePrice: 30,  gst: 18, stock: 80,  minStock: 30,  maxStock: 300,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560102', status: 'In Stock',   image: '' },
  { id: 8,   sku: 'ELE-SW-003', name: '6A Socket',              category: 'Electrical', subCategory: 'elec-switches',     brand: 'Havells',  unit: 'Piece', purchasePrice: 22,   sellingPrice: 35,   wholesalePrice: 28,  gst: 18, stock: 120, minStock: 40,  maxStock: 400,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560103', status: 'In Stock',   image: '' },
  { id: 9,   sku: 'ELE-SW-004', name: '16A Socket',             category: 'Electrical', subCategory: 'elec-switches',     brand: 'Havells',  unit: 'Piece', purchasePrice: 30,   sellingPrice: 48,   wholesalePrice: 38,  gst: 18, stock: 90,  minStock: 30,  maxStock: 300,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560104', status: 'In Stock',   image: '' },
  { id: 10,  sku: 'ELE-SW-005', name: '2-in-1 Socket',          category: 'Electrical', subCategory: 'elec-switches',     brand: 'GM',       unit: 'Piece', purchasePrice: 35,   sellingPrice: 55,   wholesalePrice: 44,  gst: 18, stock: 60,  minStock: 20,  maxStock: 200,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560105', status: 'In Stock',   image: '' },
  { id: 11,  sku: 'ELE-SW-006', name: 'Bell Push Switch',       category: 'Electrical', subCategory: 'elec-switches',     brand: 'Anchor',   unit: 'Piece', purchasePrice: 12,   sellingPrice: 20,   wholesalePrice: 16,  gst: 18, stock: 8,   minStock: 20,  maxStock: 200,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560106', status: 'Low Stock',  image: '' },
  { id: 12,  sku: 'ELE-SW-007', name: 'Fan Regulator',          category: 'Electrical', subCategory: 'elec-switches',     brand: 'Havells',  unit: 'Piece', purchasePrice: 55,   sellingPrice: 85,   wholesalePrice: 68,  gst: 18, stock: 45,  minStock: 20,  maxStock: 200,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560107', status: 'In Stock',   image: '' },
  { id: 13,  sku: 'ELE-SW-008', name: 'Modular Switch Plate',   category: 'Electrical', subCategory: 'elec-switches',     brand: 'Legrand',  unit: 'Piece', purchasePrice: 40,   sellingPrice: 65,   wholesalePrice: 52,  gst: 18, stock: 70,  minStock: 25,  maxStock: 300,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560108', status: 'In Stock',   image: '' },
  { id: 14,  sku: 'ELE-SW-009', name: 'USB Socket',             category: 'Electrical', subCategory: 'elec-switches',     brand: 'Legrand',  unit: 'Piece', purchasePrice: 120,  sellingPrice: 180,  wholesalePrice: 148, gst: 18, stock: 35,  minStock: 15,  maxStock: 150,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560109', status: 'In Stock',   image: '' },
  { id: 15,  sku: 'ELE-SW-010', name: 'Dimmer Switch',          category: 'Electrical', subCategory: 'elec-switches',     brand: 'Havells',  unit: 'Piece', purchasePrice: 85,   sellingPrice: 130,  wholesalePrice: 105, gst: 18, stock: 25,  minStock: 10,  maxStock: 100,  warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560110', status: 'In Stock',   image: '' },
  { id: 16,  sku: 'ELE-SW-011', name: 'Changeover Switch',      category: 'Electrical', subCategory: 'elec-switches',     brand: 'Siemens',  unit: 'Piece', purchasePrice: 350,  sellingPrice: 520,  wholesalePrice: 420, gst: 18, stock: 12,  minStock: 5,   maxStock: 50,   warehouse: 'WH-C', rack: 'R-01', barcode: '8901234560111', status: 'In Stock',   image: '' },

  // ── Electrical → Wires & Cables
  { id: 17,  sku: 'ELE-WR-001', name: '1.0mm Single-Core Wire (per mtr)',  category: 'Electrical', subCategory: 'elec-wires', brand: 'Polycab', unit: 'Meter', purchasePrice: 12,  sellingPrice: 18,  wholesalePrice: 14,  gst: 18, stock: 500, minStock: 100, maxStock: 2000, warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560201', status: 'In Stock',  image: '' },
  { id: 18,  sku: 'ELE-WR-002', name: '1.5mm Single-Core Wire (per mtr)',  category: 'Electrical', subCategory: 'elec-wires', brand: 'Polycab', unit: 'Meter', purchasePrice: 16,  sellingPrice: 24,  wholesalePrice: 19,  gst: 18, stock: 600, minStock: 100, maxStock: 2000, warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560202', status: 'In Stock',  image: '' },
  { id: 19,  sku: 'ELE-WR-003', name: '2.5mm Single-Core Wire (per mtr)',  category: 'Electrical', subCategory: 'elec-wires', brand: 'Polycab', unit: 'Meter', purchasePrice: 24,  sellingPrice: 36,  wholesalePrice: 29,  gst: 18, stock: 800, minStock: 150, maxStock: 3000, warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560203', status: 'In Stock',  image: '' },
  { id: 20,  sku: 'ELE-WR-004', name: '4mm Single-Core Wire (per mtr)',    category: 'Electrical', subCategory: 'elec-wires', brand: 'Finolex', unit: 'Meter', purchasePrice: 38,  sellingPrice: 56,  wholesalePrice: 46,  gst: 18, stock: 400, minStock: 100, maxStock: 1500, warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560204', status: 'In Stock',  image: '' },
  { id: 21,  sku: 'ELE-WR-005', name: '6mm Single-Core Wire (per mtr)',    category: 'Electrical', subCategory: 'elec-wires', brand: 'Finolex', unit: 'Meter', purchasePrice: 55,  sellingPrice: 82,  wholesalePrice: 66,  gst: 18, stock: 300, minStock: 80,  maxStock: 1000, warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560205', status: 'In Stock',  image: '' },
  { id: 22,  sku: 'ELE-WR-006', name: '10mm Single-Core Wire (per mtr)',   category: 'Electrical', subCategory: 'elec-wires', brand: 'Havells', unit: 'Meter', purchasePrice: 90,  sellingPrice: 135, wholesalePrice: 108, gst: 18, stock: 200, minStock: 50,  maxStock: 800,  warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560206', status: 'In Stock',  image: '' },
  { id: 23,  sku: 'ELE-WR-007', name: '2-Core Flexible Cable (per mtr)',   category: 'Electrical', subCategory: 'elec-wires', brand: 'Polycab', unit: 'Meter', purchasePrice: 28,  sellingPrice: 42,  wholesalePrice: 34,  gst: 18, stock: 350, minStock: 80,  maxStock: 1500, warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560207', status: 'In Stock',  image: '' },
  { id: 24,  sku: 'ELE-WR-008', name: '3-Core Flexible Cable (per mtr)',   category: 'Electrical', subCategory: 'elec-wires', brand: 'Polycab', unit: 'Meter', purchasePrice: 38,  sellingPrice: 58,  wholesalePrice: 46,  gst: 18, stock: 250, minStock: 60,  maxStock: 1000, warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560208', status: 'In Stock',  image: '' },
  { id: 25,  sku: 'ELE-WR-009', name: 'Coaxial Cable (per mtr)',           category: 'Electrical', subCategory: 'elec-wires', brand: 'D-Link',  unit: 'Meter', purchasePrice: 15,  sellingPrice: 25,  wholesalePrice: 19,  gst: 18, stock: 200, minStock: 50,  maxStock: 500,  warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560209', status: 'In Stock',  image: '' },
  { id: 26,  sku: 'ELE-WR-010', name: 'LAN Cable Cat6 (per mtr)',          category: 'Electrical', subCategory: 'elec-wires', brand: 'D-Link',  unit: 'Meter', purchasePrice: 18,  sellingPrice: 28,  wholesalePrice: 22,  gst: 18, stock: 300, minStock: 80,  maxStock: 1000, warehouse: 'WH-C', rack: 'R-02', barcode: '8901234560210', status: 'In Stock',  image: '' },

  // ── Electrical → MCB & Switchgear
  { id: 27,  sku: 'ELE-MC-001', name: '6A MCB',             category: 'Electrical', subCategory: 'elec-mcb', brand: 'Schneider', unit: 'Piece', purchasePrice: 85,   sellingPrice: 130,  wholesalePrice: 105, gst: 18, stock: 60,  minStock: 20, maxStock: 200,  warehouse: 'WH-C', rack: 'R-03', barcode: '8901234560301', status: 'In Stock',  image: '' },
  { id: 28,  sku: 'ELE-MC-002', name: '10A MCB',            category: 'Electrical', subCategory: 'elec-mcb', brand: 'Schneider', unit: 'Piece', purchasePrice: 90,   sellingPrice: 138,  wholesalePrice: 110, gst: 18, stock: 80,  minStock: 25, maxStock: 300,  warehouse: 'WH-C', rack: 'R-03', barcode: '8901234560302', status: 'In Stock',  image: '' },
  { id: 29,  sku: 'ELE-MC-003', name: '16A MCB',            category: 'Electrical', subCategory: 'elec-mcb', brand: 'Siemens',   unit: 'Piece', purchasePrice: 95,   sellingPrice: 145,  wholesalePrice: 115, gst: 18, stock: 100, minStock: 30, maxStock: 400,  warehouse: 'WH-C', rack: 'R-03', barcode: '8901234560303', status: 'In Stock',  image: '' },
  { id: 30,  sku: 'ELE-MC-004', name: '32A MCB',            category: 'Electrical', subCategory: 'elec-mcb', brand: 'Siemens',   unit: 'Piece', purchasePrice: 120,  sellingPrice: 185,  wholesalePrice: 148, gst: 18, stock: 50,  minStock: 15, maxStock: 200,  warehouse: 'WH-C', rack: 'R-03', barcode: '8901234560304', status: 'In Stock',  image: '' },
  { id: 31,  sku: 'ELE-MC-005', name: '63A MCB',            category: 'Electrical', subCategory: 'elec-mcb', brand: 'L&T',       unit: 'Piece', purchasePrice: 220,  sellingPrice: 340,  wholesalePrice: 272, gst: 18, stock: 25,  minStock: 10, maxStock: 100,  warehouse: 'WH-C', rack: 'R-03', barcode: '8901234560305', status: 'In Stock',  image: '' },
  { id: 32,  sku: 'ELE-MC-006', name: 'RCCB 25A',           category: 'Electrical', subCategory: 'elec-mcb', brand: 'Legrand',   unit: 'Piece', purchasePrice: 380,  sellingPrice: 580,  wholesalePrice: 465, gst: 18, stock: 20,  minStock: 8,  maxStock: 80,   warehouse: 'WH-C', rack: 'R-03', barcode: '8901234560306', status: 'In Stock',  image: '' },
  { id: 33,  sku: 'ELE-MC-007', name: 'Distribution Board 8-way', category: 'Electrical', subCategory: 'elec-mcb', brand: 'Havells', unit: 'Piece', purchasePrice: 450, sellingPrice: 680, wholesalePrice: 544, gst: 18, stock: 15,  minStock: 5,  maxStock: 50,   warehouse: 'WH-C', rack: 'R-03', barcode: '8901234560307', status: 'In Stock',  image: '' },
  { id: 34,  sku: 'ELE-MC-008', name: 'Contactor 9A',       category: 'Electrical', subCategory: 'elec-mcb', brand: 'Schneider', unit: 'Piece', purchasePrice: 320,  sellingPrice: 490,  wholesalePrice: 392, gst: 18, stock: 10,  minStock: 4,  maxStock: 40,   warehouse: 'WH-C', rack: 'R-03', barcode: '8901234560308', status: 'In Stock',  image: '' },

  // ── Electrical → Conduit & Fittings
  { id: 35,  sku: 'ELE-CD-001', name: 'PVC Conduit Pipe 20mm (per mtr)', category: 'Electrical', subCategory: 'elec-conduit', brand: 'Finolex', unit: 'Meter',  purchasePrice: 18,  sellingPrice: 28,  wholesalePrice: 22,  gst: 18, stock: 400, minStock: 100, maxStock: 2000, warehouse: 'WH-C', rack: 'R-04', barcode: '8901234560401', status: 'In Stock',  image: '' },
  { id: 36,  sku: 'ELE-CD-002', name: 'PVC Conduit Pipe 25mm (per mtr)', category: 'Electrical', subCategory: 'elec-conduit', brand: 'Finolex', unit: 'Meter',  purchasePrice: 24,  sellingPrice: 36,  wholesalePrice: 29,  gst: 18, stock: 300, minStock: 80,  maxStock: 1500, warehouse: 'WH-C', rack: 'R-04', barcode: '8901234560402', status: 'In Stock',  image: '' },
  { id: 37,  sku: 'ELE-CD-003', name: 'Conduit Bend 20mm',              category: 'Electrical', subCategory: 'elec-conduit', brand: 'Anchor',  unit: 'Piece',  purchasePrice: 5,   sellingPrice: 8,   wholesalePrice: 6,   gst: 18, stock: 200, minStock: 50,  maxStock: 1000, warehouse: 'WH-C', rack: 'R-04', barcode: '8901234560403', status: 'In Stock',  image: '' },
  { id: 38,  sku: 'ELE-CD-004', name: 'Conduit Junction Box',           category: 'Electrical', subCategory: 'elec-conduit', brand: 'Anchor',  unit: 'Piece',  purchasePrice: 12,  sellingPrice: 18,  wholesalePrice: 14,  gst: 18, stock: 150, minStock: 40,  maxStock: 600,  warehouse: 'WH-C', rack: 'R-04', barcode: '8901234560404', status: 'In Stock',  image: '' },
  { id: 39,  sku: 'ELE-CD-005', name: 'Cable Gland PG-9',              category: 'Electrical', subCategory: 'elec-conduit', brand: 'Comet',   unit: 'Piece',  purchasePrice: 8,   sellingPrice: 14,  wholesalePrice: 11,  gst: 18, stock: 100, minStock: 30,  maxStock: 500,  warehouse: 'WH-C', rack: 'R-04', barcode: '8901234560405', status: 'In Stock',  image: '' },
  { id: 40,  sku: 'ELE-CD-006', name: 'Cable Ties 100mm (per pack)',   category: 'Electrical', subCategory: 'elec-conduit', brand: 'Generic', unit: 'Pack',   purchasePrice: 20,  sellingPrice: 35,  wholesalePrice: 28,  gst: 18, stock: 80,  minStock: 25,  maxStock: 300,  warehouse: 'WH-C', rack: 'R-04', barcode: '8901234560406', status: 'In Stock',  image: '' },

  // ── Electrical → Lighting
  { id: 41,  sku: 'ELE-LT-001', name: 'LED Bulb 5W',        category: 'Electrical', subCategory: 'elec-lighting', brand: 'Philips',  unit: 'Piece', purchasePrice: 38,  sellingPrice: 58,  wholesalePrice: 46,  gst: 12, stock: 200, minStock: 50,  maxStock: 1000, warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560501', status: 'In Stock',  image: '' },
  { id: 42,  sku: 'ELE-LT-002', name: 'LED Bulb 7W',        category: 'Electrical', subCategory: 'elec-lighting', brand: 'Philips',  unit: 'Piece', purchasePrice: 45,  sellingPrice: 68,  wholesalePrice: 54,  gst: 12, stock: 250, minStock: 60,  maxStock: 1200, warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560502', status: 'In Stock',  image: '' },
  { id: 43,  sku: 'ELE-LT-003', name: 'LED Bulb 9W',        category: 'Electrical', subCategory: 'elec-lighting', brand: 'Syska',    unit: 'Piece', purchasePrice: 52,  sellingPrice: 80,  wholesalePrice: 64,  gst: 12, stock: 300, minStock: 80,  maxStock: 1500, warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560503', status: 'In Stock',  image: '' },
  { id: 44,  sku: 'ELE-LT-004', name: 'LED Bulb 12W',       category: 'Electrical', subCategory: 'elec-lighting', brand: 'Syska',    unit: 'Piece', purchasePrice: 65,  sellingPrice: 98,  wholesalePrice: 78,  gst: 12, stock: 180, minStock: 50,  maxStock: 800,  warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560504', status: 'In Stock',  image: '' },
  { id: 45,  sku: 'ELE-LT-005', name: 'LED Tube Light 20W', category: 'Electrical', subCategory: 'elec-lighting', brand: 'Havells',  unit: 'Piece', purchasePrice: 120, sellingPrice: 185, wholesalePrice: 148, gst: 12, stock: 100, minStock: 30,  maxStock: 500,  warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560505', status: 'In Stock',  image: '' },
  { id: 46,  sku: 'ELE-LT-006', name: 'LED Batten 20W',     category: 'Electrical', subCategory: 'elec-lighting', brand: 'Wipro',    unit: 'Piece', purchasePrice: 145, sellingPrice: 220, wholesalePrice: 175, gst: 12, stock: 60,  minStock: 20,  maxStock: 300,  warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560506', status: 'In Stock',  image: '' },
  { id: 47,  sku: 'ELE-LT-007', name: 'LED Panel Light 12W',category: 'Electrical', subCategory: 'elec-lighting', brand: 'Havells',  unit: 'Piece', purchasePrice: 280, sellingPrice: 420, wholesalePrice: 336, gst: 12, stock: 40,  minStock: 15,  maxStock: 200,  warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560507', status: 'In Stock',  image: '' },
  { id: 48,  sku: 'ELE-LT-008', name: 'LED Floodlight 30W', category: 'Electrical', subCategory: 'elec-lighting', brand: 'Wipro',    unit: 'Piece', purchasePrice: 380, sellingPrice: 580, wholesalePrice: 464, gst: 12, stock: 25,  minStock: 10,  maxStock: 100,  warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560508', status: 'In Stock',  image: '' },
  { id: 49,  sku: 'ELE-LT-009', name: 'Emergency Light',    category: 'Electrical', subCategory: 'elec-lighting', brand: 'Eveready', unit: 'Piece', purchasePrice: 220, sellingPrice: 340, wholesalePrice: 272, gst: 12, stock: 30,  minStock: 10,  maxStock: 150,  warehouse: 'WH-C', rack: 'R-05', barcode: '8901234560509', status: 'In Stock',  image: '' },

  // ── Electrical → Power Accessories
  { id: 50,  sku: 'ELE-PA-001', name: 'Extension Board 4-Socket', category: 'Electrical', subCategory: 'elec-accessories', brand: 'Anchor',   unit: 'Piece', purchasePrice: 120, sellingPrice: 185, wholesalePrice: 148, gst: 18, stock: 80,  minStock: 25, maxStock: 300, warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560601', status: 'In Stock',  image: '' },
  { id: 51,  sku: 'ELE-PA-002', name: 'Extension Cord 3m',        category: 'Electrical', subCategory: 'elec-accessories', brand: 'Wipro',    unit: 'Piece', purchasePrice: 85,  sellingPrice: 130, wholesalePrice: 104, gst: 18, stock: 60,  minStock: 20, maxStock: 200, warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560602', status: 'In Stock',  image: '' },
  { id: 52,  sku: 'ELE-PA-003', name: 'Multi-Plug Adaptor',       category: 'Electrical', subCategory: 'elec-accessories', brand: 'GM',       unit: 'Piece', purchasePrice: 35,  sellingPrice: 55,  wholesalePrice: 44,  gst: 18, stock: 100, minStock: 30, maxStock: 400, warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560603', status: 'In Stock',  image: '' },
  { id: 53,  sku: 'ELE-PA-004', name: 'Plug Top 6A',              category: 'Electrical', subCategory: 'elec-accessories', brand: 'Anchor',   unit: 'Piece', purchasePrice: 12,  sellingPrice: 20,  wholesalePrice: 16,  gst: 18, stock: 200, minStock: 50, maxStock: 800, warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560604', status: 'In Stock',  image: '' },
  { id: 54,  sku: 'ELE-PA-005', name: 'Plug Top 16A',             category: 'Electrical', subCategory: 'elec-accessories', brand: 'Anchor',   unit: 'Piece', purchasePrice: 18,  sellingPrice: 28,  wholesalePrice: 22,  gst: 18, stock: 150, minStock: 40, maxStock: 600, warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560605', status: 'In Stock',  image: '' },
  { id: 55,  sku: 'ELE-PA-006', name: 'Terminal Block (per strip)', category: 'Electrical', subCategory: 'elec-accessories', brand: 'Phoenix', unit: 'Strip', purchasePrice: 45,  sellingPrice: 70,  wholesalePrice: 56,  gst: 18, stock: 50,  minStock: 15, maxStock: 200, warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560606', status: 'In Stock',  image: '' },
  { id: 56,  sku: 'ELE-PA-007', name: 'Float Switch',              category: 'Electrical', subCategory: 'elec-accessories', brand: 'Havells',  unit: 'Piece', purchasePrice: 320, sellingPrice: 490, wholesalePrice: 392, gst: 18, stock: 20,  minStock: 8,  maxStock: 80,  warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560607', status: 'In Stock',  image: '' },
  { id: 57,  sku: 'ELE-PA-008', name: 'Electrical Tape (per roll)', category: 'Electrical', subCategory: 'elec-accessories', brand: '3M',      unit: 'Roll',  purchasePrice: 22,  sellingPrice: 35,  wholesalePrice: 28,  gst: 18, stock: 120, minStock: 40, maxStock: 500, warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560608', status: 'In Stock',  image: '' },
  { id: 58,  sku: 'ELE-PA-009', name: 'Digital Multimeter',        category: 'Electrical', subCategory: 'elec-accessories', brand: 'Mastech',  unit: 'Piece', purchasePrice: 380, sellingPrice: 580, wholesalePrice: 464, gst: 18, stock: 15,  minStock: 5,  maxStock: 50,  warehouse: 'WH-C', rack: 'R-06', barcode: '8901234560609', status: 'In Stock',  image: '' },

  // ── Electrical → Fans & Controls
  { id: 59,  sku: 'ELE-FN-001', name: 'Ceiling Fan 48 inch',  category: 'Electrical', subCategory: 'elec-fans', brand: 'Havells',  unit: 'Piece', purchasePrice: 1200, sellingPrice: 1850, wholesalePrice: 1480, gst: 18, stock: 20, minStock: 5,  maxStock: 50,  warehouse: 'WH-C', rack: 'R-07', barcode: '8901234560701', status: 'In Stock',  image: '' },
  { id: 60,  sku: 'ELE-FN-002', name: 'Ceiling Fan 56 inch',  category: 'Electrical', subCategory: 'elec-fans', brand: 'Usha',     unit: 'Piece', purchasePrice: 1500, sellingPrice: 2300, wholesalePrice: 1840, gst: 18, stock: 15, minStock: 4,  maxStock: 40,  warehouse: 'WH-C', rack: 'R-07', barcode: '8901234560702', status: 'In Stock',  image: '' },
  { id: 61,  sku: 'ELE-FN-003', name: 'Exhaust Fan 6 inch',   category: 'Electrical', subCategory: 'elec-fans', brand: 'Crompton', unit: 'Piece', purchasePrice: 380,  sellingPrice: 580,  wholesalePrice: 464,  gst: 18, stock: 25, minStock: 8,  maxStock: 100, warehouse: 'WH-C', rack: 'R-07', barcode: '8901234560703', status: 'In Stock',  image: '' },
  { id: 62,  sku: 'ELE-FN-004', name: 'Exhaust Fan 9 inch',   category: 'Electrical', subCategory: 'elec-fans', brand: 'Crompton', unit: 'Piece', purchasePrice: 480,  sellingPrice: 740,  wholesalePrice: 592,  gst: 18, stock: 18, minStock: 6,  maxStock: 80,  warehouse: 'WH-C', rack: 'R-07', barcode: '8901234560704', status: 'In Stock',  image: '' },
  { id: 63,  sku: 'ELE-FN-005', name: 'Fan Capacitor 2.5µF', category: 'Electrical', subCategory: 'elec-fans', brand: 'Generic',  unit: 'Piece', purchasePrice: 25,   sellingPrice: 40,   wholesalePrice: 32,   gst: 18, stock: 100,minStock: 30, maxStock: 500, warehouse: 'WH-C', rack: 'R-07', barcode: '8901234560705', status: 'In Stock',  image: '' },
  { id: 64,  sku: 'ELE-FN-006', name: 'Fan Down Rod 12 inch', category: 'Electrical', subCategory: 'elec-fans', brand: 'Generic',  unit: 'Piece', purchasePrice: 55,   sellingPrice: 85,   wholesalePrice: 68,   gst: 18, stock: 40, minStock: 15, maxStock: 200, warehouse: 'WH-C', rack: 'R-07', barcode: '8901234560706', status: 'In Stock',  image: '' },

  // ── Electrical → Doorbell & Security
  { id: 65,  sku: 'ELE-DB-001', name: 'Electric Bell 6 inch',  category: 'Electrical', subCategory: 'elec-doorbell', brand: 'Anchor',  unit: 'Piece', purchasePrice: 85,  sellingPrice: 130, wholesalePrice: 104, gst: 18, stock: 30, minStock: 10, maxStock: 150, warehouse: 'WH-C', rack: 'R-08', barcode: '8901234560801', status: 'In Stock',  image: '' },
  { id: 66,  sku: 'ELE-DB-002', name: 'Wireless Doorbell',     category: 'Electrical', subCategory: 'elec-doorbell', brand: 'Philips', unit: 'Piece', purchasePrice: 280, sellingPrice: 430, wholesalePrice: 344, gst: 18, stock: 20, minStock: 6,  maxStock: 80,  warehouse: 'WH-C', rack: 'R-08', barcode: '8901234560802', status: 'In Stock',  image: '' },
  { id: 67,  sku: 'ELE-DB-003', name: 'Bell Push Button',      category: 'Electrical', subCategory: 'elec-doorbell', brand: 'Anchor',  unit: 'Piece', purchasePrice: 15,  sellingPrice: 25,  wholesalePrice: 20,  gst: 18, stock: 80, minStock: 25, maxStock: 400, warehouse: 'WH-C', rack: 'R-08', barcode: '8901234560803', status: 'In Stock',  image: '' },
  { id: 68,  sku: 'ELE-DB-004', name: 'PIR Motion Sensor',     category: 'Electrical', subCategory: 'elec-doorbell', brand: 'Havells', unit: 'Piece', purchasePrice: 180, sellingPrice: 280, wholesalePrice: 224, gst: 18, stock: 15, minStock: 5,  maxStock: 60,  warehouse: 'WH-C', rack: 'R-08', barcode: '8901234560804', status: 'In Stock',  image: '' },
  { id: 69,  sku: 'ELE-DB-005', name: 'Indicator Lamp 240V',   category: 'Electrical', subCategory: 'elec-doorbell', brand: 'Generic', unit: 'Piece', purchasePrice: 12,  sellingPrice: 20,  wholesalePrice: 16,  gst: 18, stock: 60, minStock: 20, maxStock: 300, warehouse: 'WH-C', rack: 'R-08', barcode: '8901234560805', status: 'In Stock',  image: '' },

  // ── Electrical → Installation Accessories
  { id: 70,  sku: 'ELE-IA-001', name: 'Modular Switch Box 1-Module', category: 'Electrical', subCategory: 'elec-installation', brand: 'Anchor',  unit: 'Piece', purchasePrice: 8,   sellingPrice: 14,  wholesalePrice: 11,  gst: 18, stock: 300, minStock: 80,  maxStock: 2000, warehouse: 'WH-C', rack: 'R-09', barcode: '8901234560901', status: 'In Stock',  image: '' },
  { id: 71,  sku: 'ELE-IA-002', name: 'Modular Switch Box 3-Module', category: 'Electrical', subCategory: 'elec-installation', brand: 'Anchor',  unit: 'Piece', purchasePrice: 15,  sellingPrice: 24,  wholesalePrice: 19,  gst: 18, stock: 250, minStock: 60,  maxStock: 1500, warehouse: 'WH-C', rack: 'R-09', barcode: '8901234560902', status: 'In Stock',  image: '' },
  { id: 72,  sku: 'ELE-IA-003', name: 'Ceiling Rose',                category: 'Electrical', subCategory: 'elec-installation', brand: 'Anchor',  unit: 'Piece', purchasePrice: 10,  sellingPrice: 18,  wholesalePrice: 14,  gst: 18, stock: 200, minStock: 50,  maxStock: 1000, warehouse: 'WH-C', rack: 'R-09', barcode: '8901234560903', status: 'In Stock',  image: '' },
  { id: 73,  sku: 'ELE-IA-004', name: 'Batten Lamp Holder',          category: 'Electrical', subCategory: 'elec-installation', brand: 'Anchor',  unit: 'Piece', purchasePrice: 12,  sellingPrice: 20,  wholesalePrice: 16,  gst: 18, stock: 150, minStock: 40,  maxStock: 600,  warehouse: 'WH-C', rack: 'R-09', barcode: '8901234560904', status: 'In Stock',  image: '' },
  { id: 74,  sku: 'ELE-IA-005', name: 'Cable Clip 20mm (per pack)',  category: 'Electrical', subCategory: 'elec-installation', brand: 'Generic', unit: 'Pack',  purchasePrice: 15,  sellingPrice: 25,  wholesalePrice: 20,  gst: 18, stock: 100, minStock: 30,  maxStock: 500,  warehouse: 'WH-C', rack: 'R-09', barcode: '8901234560905', status: 'In Stock',  image: '' },
  { id: 75,  sku: 'ELE-IA-006', name: 'Earthing Rod 1m',             category: 'Electrical', subCategory: 'elec-installation', brand: 'Generic', unit: 'Piece', purchasePrice: 280, sellingPrice: 420, wholesalePrice: 336, gst: 18, stock: 15,  minStock: 5,   maxStock: 50,   warehouse: 'WH-C', rack: 'R-09', barcode: '8901234560906', status: 'In Stock',  image: '' },

  // ── Electrical → Tools
  { id: 76,  sku: 'ELE-TL-001', name: 'Voltage Tester Pen',      category: 'Electrical', subCategory: 'elec-tools', brand: 'Fluke',   unit: 'Piece', purchasePrice: 85,   sellingPrice: 130,  wholesalePrice: 104, gst: 18, stock: 40, minStock: 10, maxStock: 150, warehouse: 'WH-C', rack: 'R-10', barcode: '8901234561001', status: 'In Stock',  image: '' },
  { id: 77,  sku: 'ELE-TL-002', name: 'Insulated Screwdriver Set', category: 'Electrical', subCategory: 'elec-tools', brand: 'Stanley', unit: 'Set',   purchasePrice: 180,  sellingPrice: 280,  wholesalePrice: 224, gst: 18, stock: 25, minStock: 8,  maxStock: 100, warehouse: 'WH-C', rack: 'R-10', barcode: '8901234561002', status: 'In Stock',  image: '' },
  { id: 78,  sku: 'ELE-TL-003', name: 'Combination Pliers 8 inch', category: 'Electrical', subCategory: 'elec-tools', brand: 'Stanley', unit: 'Piece', purchasePrice: 120,  sellingPrice: 185,  wholesalePrice: 148, gst: 18, stock: 30, minStock: 10, maxStock: 120, warehouse: 'WH-C', rack: 'R-10', barcode: '8901234561003', status: 'In Stock',  image: '' },
  { id: 79,  sku: 'ELE-TL-004', name: 'Wire Stripper',             category: 'Electrical', subCategory: 'elec-tools', brand: 'Taparia', unit: 'Piece', purchasePrice: 95,   sellingPrice: 148,  wholesalePrice: 118, gst: 18, stock: 20, minStock: 6,  maxStock: 80,  warehouse: 'WH-C', rack: 'R-10', barcode: '8901234561004', status: 'In Stock',  image: '' },
  { id: 80,  sku: 'ELE-TL-005', name: 'Crimping Tool',             category: 'Electrical', subCategory: 'elec-tools', brand: 'Taparia', unit: 'Piece', purchasePrice: 220,  sellingPrice: 340,  wholesalePrice: 272, gst: 18, stock: 15, minStock: 5,  maxStock: 60,  warehouse: 'WH-C', rack: 'R-10', barcode: '8901234561005', status: 'In Stock',  image: '' },
  { id: 81,  sku: 'ELE-TL-006', name: 'Digital Clamp Meter',       category: 'Electrical', subCategory: 'elec-tools', brand: 'Mastech', unit: 'Piece', purchasePrice: 650,  sellingPrice: 980,  wholesalePrice: 784, gst: 18, stock: 10, minStock: 3,  maxStock: 40,  warehouse: 'WH-C', rack: 'R-10', barcode: '8901234561006', status: 'In Stock',  image: '' },

  // ── Electrical → Appliances & Power
  { id: 82,  sku: 'ELE-AP-001', name: 'Immersion Rod 1000W',    category: 'Electrical', subCategory: 'elec-appliances', brand: 'Bajaj',   unit: 'Piece', purchasePrice: 180,  sellingPrice: 280,  wholesalePrice: 224, gst: 18, stock: 30, minStock: 10, maxStock: 100, warehouse: 'WH-C', rack: 'R-11', barcode: '8901234561101', status: 'In Stock',  image: '' },
  { id: 83,  sku: 'ELE-AP-002', name: 'Voltage Stabilizer 5KVA',category: 'Electrical', subCategory: 'elec-appliances', brand: 'V-Guard', unit: 'Piece', purchasePrice: 3200, sellingPrice: 4800, wholesalePrice: 3840,gst: 18, stock: 5,  minStock: 2,  maxStock: 20,  warehouse: 'WH-C', rack: 'R-11', barcode: '8901234561102', status: 'In Stock',  image: '' },
  { id: 84,  sku: 'ELE-AP-003', name: 'Surge Protector 6A',    category: 'Electrical', subCategory: 'elec-appliances', brand: 'APC',     unit: 'Piece', purchasePrice: 450,  sellingPrice: 680,  wholesalePrice: 544, gst: 18, stock: 15, minStock: 5,  maxStock: 60,  warehouse: 'WH-C', rack: 'R-11', barcode: '8901234561103', status: 'In Stock',  image: '' },
  { id: 85,  sku: 'ELE-AP-004', name: 'Timer Switch 24hr',     category: 'Electrical', subCategory: 'elec-appliances', brand: 'Anchor',  unit: 'Piece', purchasePrice: 280,  sellingPrice: 420,  wholesalePrice: 336, gst: 18, stock: 12, minStock: 4,  maxStock: 50,  warehouse: 'WH-C', rack: 'R-11', barcode: '8901234561104', status: 'In Stock',  image: '' },
  { id: 86,  sku: 'ELE-AP-005', name: 'UPS 600VA',             category: 'Electrical', subCategory: 'elec-appliances', brand: 'APC',     unit: 'Piece', purchasePrice: 2800, sellingPrice: 4200, wholesalePrice: 3360,gst: 18, stock: 4,  minStock: 2,  maxStock: 15,  warehouse: 'WH-C', rack: 'R-11', barcode: '8901234561105', status: 'In Stock',  image: '' },

  // ── Plumbing → Pipes
  { id: 101, sku: 'PLB-001', name: 'PVC Pipe 1 inch (per piece)', category: 'Plumbing', subCategory: 'plumbing-pipes',    brand: 'Supreme',    unit: 'Piece',  purchasePrice: 85,   sellingPrice: 110,  wholesalePrice: 95,   gst: 18, stock: 6,  minStock: 20, maxStock: 200, warehouse: 'WH-A', rack: 'R-01', barcode: '8901234560011', status: 'Low Stock',  image: 'assets/inventory/products/pvc-pipe.png' },
  { id: 102, sku: 'PLB-002', name: 'PVC Elbow 1 inch',            category: 'Plumbing', subCategory: 'plumbing-fittings', brand: 'Finolex',    unit: 'Piece',  purchasePrice: 12,   sellingPrice: 18,   wholesalePrice: 14,   gst: 18, stock: 9,  minStock: 30, maxStock: 500, warehouse: 'WH-A', rack: 'R-02', barcode: '8901234560012', status: 'Low Stock',  image: 'assets/inventory/products/pvc-elbow.png' },
  { id: 103, sku: 'PLB-003', name: 'GI Pipe 1.5 inch (per foot)', category: 'Plumbing', subCategory: 'plumbing-pipes',    brand: 'Tata Steel', unit: 'Foot',   purchasePrice: 95,   sellingPrice: 125,  wholesalePrice: 108,  gst: 18, stock: 4,  minStock: 20, maxStock: 150, warehouse: 'WH-B', rack: 'R-03', barcode: '8901234560013', status: 'Low Stock',  image: 'assets/inventory/products/gi-pipe.png' },
  { id: 104, sku: 'PLB-004', name: 'PVC Ball Valve 1 inch',       category: 'Plumbing', subCategory: 'plumbing-valves',   brand: 'Zoloto',     unit: 'Piece',  purchasePrice: 145,  sellingPrice: 195,  wholesalePrice: 165,  gst: 18, stock: 4,  minStock: 20, maxStock: 100, warehouse: 'WH-A', rack: 'R-04', barcode: '8901234560014', status: 'Low Stock',  image: 'assets/inventory/products/ball-valve.png' },
  { id: 105, sku: 'PLB-005', name: 'Sanitary T-Trap 32mm',        category: 'Plumbing', subCategory: 'plumbing-traps',    brand: 'Astral',     unit: 'Piece',  purchasePrice: 55,   sellingPrice: 75,   wholesalePrice: 62,   gst: 18, stock: 5,  minStock: 20, maxStock: 100, warehouse: 'WH-A', rack: 'R-05', barcode: '8901234560015', status: 'Low Stock',  image: 'assets/inventory/products/t-trap.png' },

  // ── Hardware
  { id: 106, sku: 'HRD-001', name: 'Drill Bit Set (13 pcs)',      category: 'Hardware',    subCategory: 'hw-tools',         brand: 'Bosch',    unit: 'Set',    purchasePrice: 420,  sellingPrice: 580,  wholesalePrice: 500,  gst: 18, stock: 3,  minStock: 12, maxStock: 50,  warehouse: 'WH-B', rack: 'R-20', barcode: '8901234560031', status: 'Low Stock',  image: 'assets/inventory/products/drill-bits.png' },
  { id: 107, sku: 'HRD-002', name: 'Hex Bolt M10 (per kg)',       category: 'Hardware',    subCategory: 'hw-fasteners',     brand: 'Unbranded',unit: 'Kg',     purchasePrice: 85,   sellingPrice: 120,  wholesalePrice: 100,  gst: 18, stock: 15, minStock: 50, maxStock: 200, warehouse: 'WH-B', rack: 'R-21', barcode: '8901234560032', status: 'Low Stock',  image: 'assets/inventory/products/hex-bolt.png' },
  { id: 108, sku: 'HRD-003', name: 'Welding Rod 6013 (per kg)',   category: 'Hardware',    subCategory: 'hw-welding',       brand: 'D&H',      unit: 'Kg',     purchasePrice: 115,  sellingPrice: 155,  wholesalePrice: 135,  gst: 18, stock: 8,  minStock: 30, maxStock: 150, warehouse: 'WH-B', rack: 'R-22', barcode: '8901234560033', status: 'Low Stock',  image: 'assets/inventory/products/welding-rod.png' },

  // ── Agriculture → Seeds & Planting Material
  { id: 109, sku: 'AGR-SD-001', name: 'Wheat Seeds (per kg)',          category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Nuziveedu',  unit: 'Kg',    purchasePrice: 42,   sellingPrice: 65,   wholesalePrice: 52,  gst: 0,  stock: 200, minStock: 50,  maxStock: 1000, warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570101', status: 'In Stock',  image: 'assets/inventory/products/wheat.png' },
  { id: 110, sku: 'AGR-SD-002', name: 'Rice Seeds (per kg)',           category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Mahyco',     unit: 'Kg',    purchasePrice: 55,   sellingPrice: 85,   wholesalePrice: 68,  gst: 0,  stock: 150, minStock: 40,  maxStock: 800,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570102', status: 'In Stock',  image: 'assets/inventory/products/rice.png' },
  { id: 111, sku: 'AGR-SD-003', name: 'Maize Seeds (per kg)',          category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Pioneer',    unit: 'Kg',    purchasePrice: 48,   sellingPrice: 75,   wholesalePrice: 60,  gst: 0,  stock: 180, minStock: 40,  maxStock: 800,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570103', status: 'In Stock',  image: 'assets/inventory/products/maize.png' },
  { id: 117, sku: 'AGR-SD-004', name: 'Soybean Seeds (per kg)',        category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Nuziveedu',  unit: 'Kg',    purchasePrice: 65,   sellingPrice: 98,   wholesalePrice: 78,  gst: 0,  stock: 120, minStock: 30,  maxStock: 600,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570104', status: 'In Stock',  image: 'assets/inventory/products/soybean.png' },
  { id: 118, sku: 'AGR-SD-005', name: 'Cotton Seeds (per packet)',     category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Mahyco',     unit: 'Packet',purchasePrice: 220,  sellingPrice: 340,  wholesalePrice: 272, gst: 0,  stock: 80,  minStock: 20,  maxStock: 400,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570105', status: 'In Stock',  image: 'assets/inventory/products/cotton.png' },
  { id: 119, sku: 'AGR-SD-006', name: 'Groundnut Seeds (per kg)',      category: 'Agriculture', subCategory: 'agr-seeds', brand: 'IARI',        unit: 'Kg',    purchasePrice: 75,   sellingPrice: 115,  wholesalePrice: 92,  gst: 0,  stock: 100, minStock: 25,  maxStock: 500,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570106', status: 'In Stock',  image: 'assets/inventory/products/groundnut.png' },
  { id: 120, sku: 'AGR-SD-007', name: 'Sunflower Seeds (per kg)',      category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Pioneer',    unit: 'Kg',    purchasePrice: 58,   sellingPrice: 88,   wholesalePrice: 70,  gst: 0,  stock: 90,  minStock: 25,  maxStock: 400,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570107', status: 'In Stock',  image: 'assets/inventory/products/sunflower.png' },
  { id: 121, sku: 'AGR-SD-008', name: 'Mustard Seeds (per kg)',        category: 'Agriculture', subCategory: 'agr-seeds', brand: 'IARI',        unit: 'Kg',    purchasePrice: 38,   sellingPrice: 58,   wholesalePrice: 46,  gst: 0,  stock: 160, minStock: 40,  maxStock: 600,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570108', status: 'In Stock',  image: 'assets/inventory/products/mustard.png' },
  { id: 122, sku: 'AGR-SD-009', name: 'Tomato Seeds (per packet)',     category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Syngenta',   unit: 'Packet',purchasePrice: 85,   sellingPrice: 130,  wholesalePrice: 104, gst: 0,  stock: 120, minStock: 30,  maxStock: 500,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570109', status: 'In Stock',  image: 'assets/inventory/products/tomato.png' },
  { id: 123, sku: 'AGR-SD-010', name: 'Onion Seeds (per packet)',      category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Mahyco',     unit: 'Packet',purchasePrice: 65,   sellingPrice: 100,  wholesalePrice: 80,  gst: 0,  stock: 100, minStock: 25,  maxStock: 400,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570110', status: 'In Stock',  image: 'assets/inventory/products/onion.png' },
  { id: 124, sku: 'AGR-SD-011', name: 'Chilli Seeds (per packet)',     category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Syngenta',   unit: 'Packet',purchasePrice: 75,   sellingPrice: 115,  wholesalePrice: 92,  gst: 0,  stock: 80,  minStock: 20,  maxStock: 300,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570111', status: 'In Stock',  image: 'assets/inventory/products/chilli.png' },
  { id: 125, sku: 'AGR-SD-012', name: 'Vegetable Seeds Mix (packet)',  category: 'Agriculture', subCategory: 'agr-seeds', brand: 'Generic',    unit: 'Packet',purchasePrice: 45,   sellingPrice: 70,   wholesalePrice: 56,  gst: 0,  stock: 150, minStock: 40,  maxStock: 600,  warehouse: 'WH-D', rack: 'R-01', barcode: '8901234570112', status: 'In Stock',  image: 'assets/inventory/products/vegetable_mix.png' },

  // ── Agriculture → Fertilizers & Manure
  { id: 126, sku: 'AGR-FT-001', name: 'Urea 45kg Bag',                category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'IFFCO',     unit: 'Bag',   purchasePrice: 240,  sellingPrice: 280,  wholesalePrice: 260, gst: 0,  stock: 100, minStock: 30,  maxStock: 500,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570201', status: 'In Stock',  image: '' },
  { id: 127, sku: 'AGR-FT-002', name: 'DAP Fertilizer 50kg',          category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'IFFCO',     unit: 'Bag',   purchasePrice: 1080, sellingPrice: 1250, wholesalePrice: 1150,gst: 0,  stock: 80,  minStock: 20,  maxStock: 300,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570202', status: 'In Stock',  image: '' },
  { id: 128, sku: 'AGR-FT-003', name: 'NPK 19:19:19 (per kg)',        category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Coromandel',unit: 'Kg',    purchasePrice: 28,   sellingPrice: 42,   wholesalePrice: 34,  gst: 0,  stock: 200, minStock: 50,  maxStock: 1000, warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570203', status: 'In Stock',  image: '' },
  { id: 129, sku: 'AGR-FT-004', name: 'NPK 12:32:16 (per kg)',        category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Coromandel',unit: 'Kg',    purchasePrice: 30,   sellingPrice: 46,   wholesalePrice: 37,  gst: 0,  stock: 150, minStock: 40,  maxStock: 800,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570204', status: 'In Stock',  image: '' },
  { id: 130, sku: 'AGR-FT-005', name: 'MOP Potash (per kg)',          category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'IFFCO',     unit: 'Kg',    purchasePrice: 18,   sellingPrice: 28,   wholesalePrice: 22,  gst: 0,  stock: 180, minStock: 50,  maxStock: 800,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570205', status: 'In Stock',  image: '' },
  { id: 131, sku: 'AGR-FT-006', name: 'Zinc Sulphate (per kg)',       category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Generic',   unit: 'Kg',    purchasePrice: 45,   sellingPrice: 68,   wholesalePrice: 55,  gst: 0,  stock: 100, minStock: 25,  maxStock: 400,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570206', status: 'In Stock',  image: '' },
  { id: 132, sku: 'AGR-FT-007', name: 'Vermicompost (per kg)',        category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Generic',   unit: 'Kg',    purchasePrice: 8,    sellingPrice: 15,   wholesalePrice: 12,  gst: 0,  stock: 500, minStock: 100, maxStock: 2000, warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570207', status: 'In Stock',  image: '' },
  { id: 133, sku: 'AGR-FT-008', name: 'Neem Cake (per kg)',           category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Generic',   unit: 'Kg',    purchasePrice: 12,   sellingPrice: 20,   wholesalePrice: 16,  gst: 0,  stock: 300, minStock: 80,  maxStock: 1500, warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570208', status: 'In Stock',  image: '' },
  { id: 134, sku: 'AGR-FT-009', name: 'Organic Compost 25kg Bag',    category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Generic',   unit: 'Bag',   purchasePrice: 95,   sellingPrice: 145,  wholesalePrice: 116, gst: 0,  stock: 150, minStock: 40,  maxStock: 600,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570209', status: 'In Stock',  image: '' },
  { id: 135, sku: 'AGR-FT-010', name: 'Bio-Fertilizer (per litre)',  category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Jai Kisan', unit: 'Litre', purchasePrice: 85,   sellingPrice: 130,  wholesalePrice: 104, gst: 0,  stock: 80,  minStock: 20,  maxStock: 300,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570210', status: 'In Stock',  image: '' },
  { id: 136, sku: 'AGR-FT-011', name: 'Humic Acid (per litre)',      category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Generic',   unit: 'Litre', purchasePrice: 120,  sellingPrice: 185,  wholesalePrice: 148, gst: 0,  stock: 60,  minStock: 15,  maxStock: 200,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570211', status: 'In Stock',  image: '' },
  { id: 137, sku: 'AGR-FT-012', name: 'Micronutrient Mixture (kg)',  category: 'Agriculture', subCategory: 'agr-fertilizers', brand: 'Coromandel',unit: 'Kg',    purchasePrice: 55,   sellingPrice: 85,   wholesalePrice: 68,  gst: 0,  stock: 100, minStock: 25,  maxStock: 400,  warehouse: 'WH-D', rack: 'R-02', barcode: '8901234570212', status: 'In Stock',  image: '' },

  // ── Agriculture → Pesticides & Crop Protection
  { id: 138, sku: 'AGR-PP-001', name: 'Insecticide 250ml',           category: 'Agriculture', subCategory: 'agr-pesticides', brand: 'Bayer',     unit: 'Bottle',purchasePrice: 180,  sellingPrice: 280,  wholesalePrice: 224, gst: 18, stock: 80,  minStock: 20, maxStock: 300,  warehouse: 'WH-D', rack: 'R-03', barcode: '8901234570301', status: 'In Stock',  image: '' },
  { id: 139, sku: 'AGR-PP-002', name: 'Fungicide 250ml',             category: 'Agriculture', subCategory: 'agr-pesticides', brand: 'Syngenta',  unit: 'Bottle',purchasePrice: 220,  sellingPrice: 340,  wholesalePrice: 272, gst: 18, stock: 60,  minStock: 15, maxStock: 200,  warehouse: 'WH-D', rack: 'R-03', barcode: '8901234570302', status: 'In Stock',  image: '' },
  { id: 140, sku: 'AGR-PP-003', name: 'Herbicide 500ml',             category: 'Agriculture', subCategory: 'agr-pesticides', brand: 'BASF',      unit: 'Bottle',purchasePrice: 280,  sellingPrice: 420,  wholesalePrice: 336, gst: 18, stock: 50,  minStock: 12, maxStock: 150,  warehouse: 'WH-D', rack: 'R-03', barcode: '8901234570303', status: 'In Stock',  image: '' },
  { id: 141, sku: 'AGR-PP-004', name: 'Neem Oil 1 Litre',            category: 'Agriculture', subCategory: 'agr-pesticides', brand: 'Generic',   unit: 'Litre', purchasePrice: 95,   sellingPrice: 148,  wholesalePrice: 118, gst: 5,  stock: 100, minStock: 25, maxStock: 400,  warehouse: 'WH-D', rack: 'R-03', barcode: '8901234570304', status: 'In Stock',  image: '' },
  { id: 142, sku: 'AGR-PP-005', name: 'Bio-Pesticide 500ml',         category: 'Agriculture', subCategory: 'agr-pesticides', brand: 'Jai Kisan', unit: 'Bottle',purchasePrice: 150,  sellingPrice: 230,  wholesalePrice: 184, gst: 5,  stock: 70,  minStock: 18, maxStock: 250,  warehouse: 'WH-D', rack: 'R-03', barcode: '8901234570305', status: 'In Stock',  image: '' },
  { id: 143, sku: 'AGR-PP-006', name: 'Weed Killer 1 Litre',         category: 'Agriculture', subCategory: 'agr-pesticides', brand: 'Bayer',     unit: 'Litre', purchasePrice: 320,  sellingPrice: 490,  wholesalePrice: 392, gst: 18, stock: 40,  minStock: 10, maxStock: 150,  warehouse: 'WH-D', rack: 'R-03', barcode: '8901234570306', status: 'In Stock',  image: '' },
  { id: 144, sku: 'AGR-PP-007', name: 'Plant Growth Regulator 100ml',category: 'Agriculture', subCategory: 'agr-pesticides', brand: 'Syngenta',  unit: 'Bottle',purchasePrice: 180,  sellingPrice: 275,  wholesalePrice: 220, gst: 18, stock: 50,  minStock: 12, maxStock: 200,  warehouse: 'WH-D', rack: 'R-03', barcode: '8901234570307', status: 'In Stock',  image: '' },
  { id: 145, sku: 'AGR-PP-008', name: 'Sticker/Spreader 100ml',      category: 'Agriculture', subCategory: 'agr-pesticides', brand: 'Generic',   unit: 'Bottle',purchasePrice: 45,   sellingPrice: 70,   wholesalePrice: 56,  gst: 18, stock: 80,  minStock: 20, maxStock: 400,  warehouse: 'WH-D', rack: 'R-03', barcode: '8901234570308', status: 'In Stock',  image: '' },

  // ── Agriculture → Irrigation (keep existing two, renumbered)
  { id: 146, sku: 'AGR-IR-001', name: 'Drip Irrigation Tube 16mm (mtr)', category: 'Agriculture', subCategory: 'agr-irrigation', brand: 'Jain',    unit: 'Meter',  purchasePrice: 8,   sellingPrice: 12,  wholesalePrice: 10,  gst: 5,  stock: 500, minStock: 100, maxStock: 2000, warehouse: 'WH-D', rack: 'R-04', barcode: '8901234560042', status: 'In Stock',  image: 'assets/inventory/products/drip-tube.png' },

  // ── Agriculture → Shade & Covering (keep existing two, renumbered)
  { id: 147, sku: 'AGR-CV-001', name: 'Shade Net Green (per sqm)',        category: 'Agriculture', subCategory: 'agr-covering',   brand: 'Garware',  unit: 'Sq.Mtr', purchasePrice: 28,  sellingPrice: 40,  wholesalePrice: 33,  gst: 5,  stock: 80,  minStock: 20,  maxStock: 500,  warehouse: 'WH-D', rack: 'R-05', barcode: '8901234560041', status: 'In Stock',  image: 'assets/inventory/products/shade-net.png' },
  { id: 148, sku: 'AGR-CV-002', name: 'Tarpaulin 15x20 ft',               category: 'Agriculture', subCategory: 'agr-covering',   brand: 'Singhal',  unit: 'Piece',  purchasePrice: 580, sellingPrice: 780, wholesalePrice: 660, gst: 12, stock: 25,  minStock: 8,   maxStock: 100,  warehouse: 'WH-D', rack: 'R-05', barcode: '8901234560043', status: 'In Stock',  image: 'assets/inventory/products/tarpaulin.png' },

  // ── Paint → Interior Wall Paints
  { id: 149, sku: 'PNT-IN-001', name: 'Interior Emulsion White 20L',       category: 'Paint', subCategory: 'paint-interior',   brand: 'Asian Paints', unit: 'Bucket', purchasePrice: 2200, sellingPrice: 2850, wholesalePrice: 2500, gst: 18, stock: 30, minStock: 8,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-40', barcode: '8901234580001', status: 'In Stock',  image: '' },
  { id: 150, sku: 'PNT-IN-002', name: 'Interior Emulsion White 10L',       category: 'Paint', subCategory: 'paint-interior',   brand: 'Asian Paints', unit: 'Bucket', purchasePrice: 1180, sellingPrice: 1480, wholesalePrice: 1300, gst: 18, stock: 40, minStock: 10, maxStock: 100, warehouse: 'WH-E', rack: 'R-40', barcode: '8901234580002', status: 'In Stock',  image: '' },
  { id: 151, sku: 'PNT-IN-003', name: 'Interior Emulsion White 4L',        category: 'Paint', subCategory: 'paint-interior',   brand: 'Asian Paints', unit: 'Bucket', purchasePrice: 520,  sellingPrice: 650,  wholesalePrice: 580,  gst: 18, stock: 60, minStock: 15, maxStock: 150, warehouse: 'WH-E', rack: 'R-40', barcode: '8901234580003', status: 'In Stock',  image: '' },
  { id: 152, sku: 'PNT-IN-004', name: 'Interior Emulsion White 1L',        category: 'Paint', subCategory: 'paint-interior',   brand: 'Berger',       unit: 'Litre',  purchasePrice: 145,  sellingPrice: 185,  wholesalePrice: 165,  gst: 18, stock: 80, minStock: 20, maxStock: 200, warehouse: 'WH-E', rack: 'R-40', barcode: '8901234580004', status: 'In Stock',  image: '' },
  { id: 153, sku: 'PNT-IN-005', name: 'Premium Interior Emulsion 20L',     category: 'Paint', subCategory: 'paint-interior',   brand: 'Berger',       unit: 'Bucket', purchasePrice: 3200, sellingPrice: 4100, wholesalePrice: 3600, gst: 18, stock: 15, minStock: 4,  maxStock: 50,  warehouse: 'WH-E', rack: 'R-40', barcode: '8901234580005', status: 'In Stock',  image: '' },
  { id: 154, sku: 'PNT-IN-006', name: 'Washable Interior Paint 20L',       category: 'Paint', subCategory: 'paint-interior',   brand: 'Nerolac',      unit: 'Bucket', purchasePrice: 2400, sellingPrice: 3100, wholesalePrice: 2750, gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-40', barcode: '8901234580006', status: 'In Stock',  image: '' },
  { id: 155, sku: 'PNT-IN-007', name: 'Acrylic Distemper 20kg',            category: 'Paint', subCategory: 'paint-interior',   brand: 'Asian Paints', unit: 'Bucket', purchasePrice: 850,  sellingPrice: 1100, wholesalePrice: 980,  gst: 18, stock: 25, minStock: 8,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-40', barcode: '8901234580007', status: 'In Stock',  image: '' },
  { id: 156, sku: 'PNT-IN-008', name: 'Matte Finish Paint 20L',            category: 'Paint', subCategory: 'paint-interior',   brand: 'Dulux',        unit: 'Bucket', purchasePrice: 2600, sellingPrice: 3350, wholesalePrice: 2950, gst: 18, stock: 12, minStock: 4,  maxStock: 40,  warehouse: 'WH-E', rack: 'R-40', barcode: '8901234580008', status: 'In Stock',  image: '' },

  // ── Paint → Exterior Wall Paints
  { id: 157, sku: 'PNT-EX-001', name: 'Exterior Emulsion White 20L',       category: 'Paint', subCategory: 'paint-exterior',   brand: 'Asian Paints', unit: 'Bucket', purchasePrice: 2600, sellingPrice: 3300, wholesalePrice: 2900, gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-41', barcode: '8901234580009', status: 'In Stock',  image: '' },
  { id: 158, sku: 'PNT-EX-002', name: 'Weatherproof Exterior Paint 20L',   category: 'Paint', subCategory: 'paint-exterior',   brand: 'Berger',       unit: 'Bucket', purchasePrice: 2800, sellingPrice: 3600, wholesalePrice: 3100, gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-41', barcode: '8901234580010', status: 'In Stock',  image: '' },
  { id: 159, sku: 'PNT-EX-003', name: 'Acrylic Exterior Paint 20L',        category: 'Paint', subCategory: 'paint-exterior',   brand: 'Nerolac',      unit: 'Bucket', purchasePrice: 2200, sellingPrice: 2800, wholesalePrice: 2500, gst: 18, stock: 18, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-41', barcode: '8901234580011', status: 'In Stock',  image: '' },
  { id: 160, sku: 'PNT-EX-004', name: 'Premium Weather Coat 20L',          category: 'Paint', subCategory: 'paint-exterior',   brand: 'Asian Paints', unit: 'Bucket', purchasePrice: 3400, sellingPrice: 4400, wholesalePrice: 3850, gst: 18, stock: 10, minStock: 3,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-41', barcode: '8901234580012', status: 'In Stock',  image: '' },
  { id: 161, sku: 'PNT-EX-005', name: 'Heat Reflective Exterior Paint 20L',category: 'Paint', subCategory: 'paint-exterior',   brand: 'Berger',       unit: 'Bucket', purchasePrice: 3800, sellingPrice: 4900, wholesalePrice: 4300, gst: 18, stock: 8,  minStock: 2,  maxStock: 25,  warehouse: 'WH-E', rack: 'R-41', barcode: '8901234580013', status: 'In Stock',  image: '' },
  { id: 162, sku: 'PNT-EX-006', name: 'Textured Exterior Paint 20L',       category: 'Paint', subCategory: 'paint-exterior',   brand: 'Nippon',       unit: 'Bucket', purchasePrice: 2000, sellingPrice: 2600, wholesalePrice: 2300, gst: 18, stock: 15, minStock: 4,  maxStock: 50,  warehouse: 'WH-E', rack: 'R-41', barcode: '8901234580014', status: 'In Stock',  image: '' },

  // ── Paint → Primers & Sealers
  { id: 163, sku: 'PNT-PR-001', name: 'Water-Based Wall Primer 20L',       category: 'Paint', subCategory: 'paint-primer',     brand: 'Asian Paints', unit: 'Bucket', purchasePrice: 1100, sellingPrice: 1450, wholesalePrice: 1270, gst: 18, stock: 30, minStock: 8,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-42', barcode: '8901234580015', status: 'In Stock',  image: '' },
  { id: 164, sku: 'PNT-PR-002', name: 'Exterior Wall Primer 20L',          category: 'Paint', subCategory: 'paint-primer',     brand: 'Berger',       unit: 'Bucket', purchasePrice: 1200, sellingPrice: 1580, wholesalePrice: 1380, gst: 18, stock: 25, minStock: 6,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-42', barcode: '8901234580016', status: 'In Stock',  image: '' },
  { id: 165, sku: 'PNT-PR-003', name: 'Acrylic Primer 10L',                category: 'Paint', subCategory: 'paint-primer',     brand: 'Nerolac',      unit: 'Bucket', purchasePrice: 680,  sellingPrice: 880,  wholesalePrice: 780,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-42', barcode: '8901234580017', status: 'In Stock',  image: '' },
  { id: 166, sku: 'PNT-PR-004', name: 'Red Oxide Primer 4L',               category: 'Paint', subCategory: 'paint-primer',     brand: 'Asian Paints', unit: 'Tin',    purchasePrice: 380,  sellingPrice: 490,  wholesalePrice: 430,  gst: 18, stock: 30, minStock: 8,  maxStock: 100, warehouse: 'WH-E', rack: 'R-42', barcode: '8901234580018', status: 'In Stock',  image: '' },
  { id: 167, sku: 'PNT-PR-005', name: 'Metal Primer 4L',                   category: 'Paint', subCategory: 'paint-primer',     brand: 'Berger',       unit: 'Tin',    purchasePrice: 420,  sellingPrice: 540,  wholesalePrice: 475,  gst: 18, stock: 20, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-42', barcode: '8901234580019', status: 'In Stock',  image: '' },
  { id: 168, sku: 'PNT-PR-006', name: 'Wood Primer 4L',                    category: 'Paint', subCategory: 'paint-primer',     brand: 'Nerolac',      unit: 'Tin',    purchasePrice: 350,  sellingPrice: 450,  wholesalePrice: 395,  gst: 18, stock: 20, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-42', barcode: '8901234580020', status: 'In Stock',  image: '' },
  { id: 169, sku: 'PNT-PR-007', name: 'Epoxy Primer 4L',                   category: 'Paint', subCategory: 'paint-primer',     brand: 'Nippon',       unit: 'Tin',    purchasePrice: 680,  sellingPrice: 880,  wholesalePrice: 780,  gst: 18, stock: 10, minStock: 3,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-42', barcode: '8901234580021', status: 'In Stock',  image: '' },

  // ── Paint → Wall Putty & Fillers
  { id: 170, sku: 'PNT-PU-001', name: 'White Cement Wall Putty 40kg',      category: 'Paint', subCategory: 'paint-putty',      brand: 'Asian Paints', unit: 'Bag',    purchasePrice: 680,  sellingPrice: 850,  wholesalePrice: 765,  gst: 12, stock: 40, minStock: 10, maxStock: 120, warehouse: 'WH-E', rack: 'R-43', barcode: '8901234580022', status: 'In Stock',  image: '' },
  { id: 171, sku: 'PNT-PU-002', name: 'White Cement Wall Putty 20kg',      category: 'Paint', subCategory: 'paint-putty',      brand: 'Berger',       unit: 'Bag',    purchasePrice: 360,  sellingPrice: 450,  wholesalePrice: 405,  gst: 12, stock: 50, minStock: 12, maxStock: 150, warehouse: 'WH-E', rack: 'R-43', barcode: '8901234580023', status: 'In Stock',  image: '' },
  { id: 172, sku: 'PNT-PU-003', name: 'Acrylic Wall Putty 20kg',           category: 'Paint', subCategory: 'paint-putty',      brand: 'Nerolac',      unit: 'Bag',    purchasePrice: 480,  sellingPrice: 620,  wholesalePrice: 555,  gst: 12, stock: 30, minStock: 8,  maxStock: 100, warehouse: 'WH-E', rack: 'R-43', barcode: '8901234580024', status: 'In Stock',  image: '' },
  { id: 173, sku: 'PNT-PU-004', name: 'Ready-Mix Wall Putty 5kg',          category: 'Paint', subCategory: 'paint-putty',      brand: 'Asian Paints', unit: 'Bucket', purchasePrice: 145,  sellingPrice: 185,  wholesalePrice: 165,  gst: 12, stock: 60, minStock: 15, maxStock: 200, warehouse: 'WH-E', rack: 'R-43', barcode: '8901234580025', status: 'In Stock',  image: '' },
  { id: 174, sku: 'PNT-PU-005', name: 'Crack Filler 1kg',                  category: 'Paint', subCategory: 'paint-putty',      brand: 'Fevicol',      unit: 'Kg',     purchasePrice: 85,   sellingPrice: 110,  wholesalePrice: 98,   gst: 12, stock: 80, minStock: 20, maxStock: 300, warehouse: 'WH-E', rack: 'R-43', barcode: '8901234580026', status: 'In Stock',  image: '' },
  { id: 175, sku: 'PNT-PU-006', name: 'Wood Filler 1kg',                   category: 'Paint', subCategory: 'paint-putty',      brand: 'Berger',       unit: 'Kg',     purchasePrice: 95,   sellingPrice: 125,  wholesalePrice: 110,  gst: 12, stock: 40, minStock: 10, maxStock: 150, warehouse: 'WH-E', rack: 'R-43', barcode: '8901234580027', status: 'In Stock',  image: '' },

  // ── Paint → Wood Paint & Coatings
  { id: 176, sku: 'PNT-WD-001', name: 'Wood Primer 4L',                    category: 'Paint', subCategory: 'paint-wood',       brand: 'Asian Paints', unit: 'Tin',    purchasePrice: 350,  sellingPrice: 450,  wholesalePrice: 395,  gst: 18, stock: 15, minStock: 4,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-44', barcode: '8901234580028', status: 'In Stock',  image: '' },
  { id: 177, sku: 'PNT-WD-002', name: 'Wood Enamel 4L',                    category: 'Paint', subCategory: 'paint-wood',       brand: 'Berger',       unit: 'Tin',    purchasePrice: 520,  sellingPrice: 680,  wholesalePrice: 600,  gst: 18, stock: 15, minStock: 4,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-44', barcode: '8901234580029', status: 'In Stock',  image: '' },
  { id: 178, sku: 'PNT-WD-003', name: 'PU Clear Coat 4L',                  category: 'Paint', subCategory: 'paint-wood',       brand: 'Nerolac',      unit: 'Tin',    purchasePrice: 980,  sellingPrice: 1280, wholesalePrice: 1120, gst: 18, stock: 8,  minStock: 2,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-44', barcode: '8901234580030', status: 'In Stock',  image: '' },
  { id: 179, sku: 'PNT-WD-004', name: 'Wood Polish 1L',                    category: 'Paint', subCategory: 'paint-wood',       brand: 'Asian Paints', unit: 'Litre',  purchasePrice: 220,  sellingPrice: 290,  wholesalePrice: 255,  gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-44', barcode: '8901234580031', status: 'In Stock',  image: '' },
  { id: 180, sku: 'PNT-WD-005', name: 'Teak Wood Polish 1L',               category: 'Paint', subCategory: 'paint-wood',       brand: 'Berger',       unit: 'Litre',  purchasePrice: 240,  sellingPrice: 315,  wholesalePrice: 275,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-44', barcode: '8901234580032', status: 'In Stock',  image: '' },
  { id: 181, sku: 'PNT-WD-006', name: 'Wood Sealer 1L',                    category: 'Paint', subCategory: 'paint-wood',       brand: 'Nippon',       unit: 'Litre',  purchasePrice: 180,  sellingPrice: 240,  wholesalePrice: 210,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-44', barcode: '8901234580033', status: 'In Stock',  image: '' },

  // ── Paint → Metal Paint & Coatings
  { id: 182, sku: 'PNT-MT-001', name: 'Red Oxide Primer 4L',               category: 'Paint', subCategory: 'paint-metal',      brand: 'Asian Paints', unit: 'Tin',    purchasePrice: 380,  sellingPrice: 490,  wholesalePrice: 430,  gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-45', barcode: '8901234580034', status: 'In Stock',  image: '' },
  { id: 183, sku: 'PNT-MT-002', name: 'Synthetic Enamel Black 4L',         category: 'Paint', subCategory: 'paint-metal',      brand: 'Berger',       unit: 'Tin',    purchasePrice: 480,  sellingPrice: 620,  wholesalePrice: 550,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-45', barcode: '8901234580035', status: 'In Stock',  image: '' },
  { id: 184, sku: 'PNT-MT-003', name: 'Synthetic Enamel White 4L',         category: 'Paint', subCategory: 'paint-metal',      brand: 'Berger',       unit: 'Tin',    purchasePrice: 480,  sellingPrice: 620,  wholesalePrice: 550,  gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-45', barcode: '8901234580036', status: 'In Stock',  image: '' },
  { id: 185, sku: 'PNT-MT-004', name: 'Aluminium Paint 4L',                category: 'Paint', subCategory: 'paint-metal',      brand: 'Asian Paints', unit: 'Tin',    purchasePrice: 520,  sellingPrice: 680,  wholesalePrice: 600,  gst: 18, stock: 15, minStock: 4,  maxStock: 50,  warehouse: 'WH-E', rack: 'R-45', barcode: '8901234580037', status: 'In Stock',  image: '' },
  { id: 186, sku: 'PNT-MT-005', name: 'Anti-Rust Paint 1L',                category: 'Paint', subCategory: 'paint-metal',      brand: 'Nerolac',      unit: 'Litre',  purchasePrice: 185,  sellingPrice: 245,  wholesalePrice: 215,  gst: 18, stock: 30, minStock: 8,  maxStock: 100, warehouse: 'WH-E', rack: 'R-45', barcode: '8901234580038', status: 'In Stock',  image: '' },
  { id: 187, sku: 'PNT-MT-006', name: 'Heat Resistant Paint 1L',           category: 'Paint', subCategory: 'paint-metal',      brand: 'Berger',       unit: 'Litre',  purchasePrice: 280,  sellingPrice: 370,  wholesalePrice: 325,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-45', barcode: '8901234580039', status: 'In Stock',  image: '' },
  { id: 188, sku: 'PNT-MT-007', name: 'Machinery Enamel 4L',               category: 'Paint', subCategory: 'paint-metal',      brand: 'Nippon',       unit: 'Tin',    purchasePrice: 520,  sellingPrice: 680,  wholesalePrice: 600,  gst: 18, stock: 12, minStock: 3,  maxStock: 40,  warehouse: 'WH-E', rack: 'R-45', barcode: '8901234580040', status: 'In Stock',  image: '' },
  { id: 189, sku: 'PNT-MT-008', name: 'Metal Spray Paint 400ml',           category: 'Paint', subCategory: 'paint-metal',      brand: 'Nippon',       unit: 'Can',    purchasePrice: 95,   sellingPrice: 125,  wholesalePrice: 110,  gst: 18, stock: 50, minStock: 12, maxStock: 200, warehouse: 'WH-E', rack: 'R-45', barcode: '8901234580041', status: 'In Stock',  image: '' },

  // ── Paint → Enamel Paints
  { id: 190, sku: 'PNT-EN-001', name: 'Synthetic Enamel White 4L',         category: 'Paint', subCategory: 'paint-enamel',     brand: 'Asian Paints', unit: 'Tin',    purchasePrice: 480,  sellingPrice: 620,  wholesalePrice: 550,  gst: 18, stock: 30, minStock: 8,  maxStock: 100, warehouse: 'WH-E', rack: 'R-46', barcode: '8901234580042', status: 'In Stock',  image: '' },
  { id: 191, sku: 'PNT-EN-002', name: 'Synthetic Enamel Black 4L',         category: 'Paint', subCategory: 'paint-enamel',     brand: 'Asian Paints', unit: 'Tin',    purchasePrice: 480,  sellingPrice: 620,  wholesalePrice: 550,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-46', barcode: '8901234580043', status: 'In Stock',  image: '' },
  { id: 192, sku: 'PNT-EN-003', name: 'Synthetic Enamel Red 1L',           category: 'Paint', subCategory: 'paint-enamel',     brand: 'Berger',       unit: 'Litre',  purchasePrice: 135,  sellingPrice: 175,  wholesalePrice: 155,  gst: 18, stock: 30, minStock: 8,  maxStock: 120, warehouse: 'WH-E', rack: 'R-46', barcode: '8901234580044', status: 'In Stock',  image: '' },
  { id: 193, sku: 'PNT-EN-004', name: 'Synthetic Enamel Blue 1L',          category: 'Paint', subCategory: 'paint-enamel',     brand: 'Berger',       unit: 'Litre',  purchasePrice: 135,  sellingPrice: 175,  wholesalePrice: 155,  gst: 18, stock: 25, minStock: 6,  maxStock: 100, warehouse: 'WH-E', rack: 'R-46', barcode: '8901234580045', status: 'In Stock',  image: '' },
  { id: 194, sku: 'PNT-EN-005', name: 'Synthetic Enamel Green 1L',         category: 'Paint', subCategory: 'paint-enamel',     brand: 'Berger',       unit: 'Litre',  purchasePrice: 135,  sellingPrice: 175,  wholesalePrice: 155,  gst: 18, stock: 20, minStock: 5,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-46', barcode: '8901234580046', status: 'In Stock',  image: '' },
  { id: 195, sku: 'PNT-EN-006', name: 'High Gloss Enamel 4L',              category: 'Paint', subCategory: 'paint-enamel',     brand: 'Nerolac',      unit: 'Tin',    purchasePrice: 520,  sellingPrice: 680,  wholesalePrice: 600,  gst: 18, stock: 15, minStock: 4,  maxStock: 50,  warehouse: 'WH-E', rack: 'R-46', barcode: '8901234580047', status: 'In Stock',  image: '' },

  // ── Paint → Waterproofing
  { id: 196, sku: 'PNT-WP-001', name: 'Terrace Waterproofing 20L',         category: 'Paint', subCategory: 'paint-waterproof',  brand: 'Dr. Fixit',   unit: 'Litre',  purchasePrice: 2200, sellingPrice: 2850, wholesalePrice: 2500, gst: 18, stock: 15, minStock: 4,  maxStock: 50,  warehouse: 'WH-E', rack: 'R-47', barcode: '8901234580048', status: 'In Stock',  image: '' },
  { id: 197, sku: 'PNT-WP-002', name: 'Roof Waterproofing Coating 20L',    category: 'Paint', subCategory: 'paint-waterproof',  brand: 'Berger',      unit: 'Litre',  purchasePrice: 2000, sellingPrice: 2600, wholesalePrice: 2300, gst: 18, stock: 12, minStock: 3,  maxStock: 40,  warehouse: 'WH-E', rack: 'R-47', barcode: '8901234580049', status: 'In Stock',  image: '' },
  { id: 198, sku: 'PNT-WP-003', name: 'Bathroom Waterproofing 10kg',       category: 'Paint', subCategory: 'paint-waterproof',  brand: 'Dr. Fixit',   unit: 'Kg',     purchasePrice: 850,  sellingPrice: 1100, wholesalePrice: 980,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-47', barcode: '8901234580050', status: 'In Stock',  image: '' },
  { id: 199, sku: 'PNT-WP-004', name: 'Damp Proof Coating 20L',            category: 'Paint', subCategory: 'paint-waterproof',  brand: 'Asian Paints',unit: 'Litre',  purchasePrice: 1800, sellingPrice: 2350, wholesalePrice: 2060, gst: 18, stock: 10, minStock: 3,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-47', barcode: '8901234580051', status: 'In Stock',  image: '' },
  { id: 200, sku: 'PNT-WP-005', name: 'Waterproofing Chemical 5L',         category: 'Paint', subCategory: 'paint-waterproof',  brand: 'Dr. Fixit',   unit: 'Litre',  purchasePrice: 480,  sellingPrice: 630,  wholesalePrice: 555,  gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-47', barcode: '8901234580052', status: 'In Stock',  image: '' },
  { id: 201, sku: 'PNT-WP-006', name: 'Crack Sealant 1kg',                 category: 'Paint', subCategory: 'paint-waterproof',  brand: 'Fevicol',     unit: 'Kg',     purchasePrice: 120,  sellingPrice: 160,  wholesalePrice: 140,  gst: 18, stock: 50, minStock: 12, maxStock: 200, warehouse: 'WH-E', rack: 'R-47', barcode: '8901234580053', status: 'In Stock',  image: '' },

  // ── Paint → Texture & Decorative
  { id: 202, sku: 'PNT-TX-001', name: 'Wall Texture White 20kg',           category: 'Paint', subCategory: 'paint-texture',    brand: 'Asian Paints', unit: 'Kg',     purchasePrice: 680,  sellingPrice: 880,  wholesalePrice: 780,  gst: 18, stock: 15, minStock: 4,  maxStock: 50,  warehouse: 'WH-E', rack: 'R-48', barcode: '8901234580054', status: 'In Stock',  image: '' },
  { id: 203, sku: 'PNT-TX-002', name: 'Sand Texture 20kg',                 category: 'Paint', subCategory: 'paint-texture',    brand: 'Berger',       unit: 'Kg',     purchasePrice: 620,  sellingPrice: 800,  wholesalePrice: 710,  gst: 18, stock: 12, minStock: 3,  maxStock: 40,  warehouse: 'WH-E', rack: 'R-48', barcode: '8901234580055', status: 'In Stock',  image: '' },
  { id: 204, sku: 'PNT-TX-003', name: 'Stone Texture 20kg',                category: 'Paint', subCategory: 'paint-texture',    brand: 'Nippon',       unit: 'Kg',     purchasePrice: 720,  sellingPrice: 940,  wholesalePrice: 830,  gst: 18, stock: 10, minStock: 3,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-48', barcode: '8901234580056', status: 'In Stock',  image: '' },
  { id: 205, sku: 'PNT-TX-004', name: 'Metallic Finish Paint 1L',          category: 'Paint', subCategory: 'paint-texture',    brand: 'Asian Paints', unit: 'Litre',  purchasePrice: 380,  sellingPrice: 490,  wholesalePrice: 435,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-48', barcode: '8901234580057', status: 'In Stock',  image: '' },
  { id: 206, sku: 'PNT-TX-005', name: 'Marble Finish Coating 4L',          category: 'Paint', subCategory: 'paint-texture',    brand: 'Indigo',       unit: 'Tin',    purchasePrice: 780,  sellingPrice: 1020, wholesalePrice: 900,  gst: 18, stock: 8,  minStock: 2,  maxStock: 25,  warehouse: 'WH-E', rack: 'R-48', barcode: '8901234580058', status: 'In Stock',  image: '' },
  { id: 207, sku: 'PNT-TX-006', name: 'Decorative Texture 20kg',           category: 'Paint', subCategory: 'paint-texture',    brand: 'Berger',       unit: 'Kg',     purchasePrice: 650,  sellingPrice: 850,  wholesalePrice: 750,  gst: 18, stock: 10, minStock: 3,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-48', barcode: '8901234580059', status: 'In Stock',  image: '' },

  // ── Paint → Floor Paint & Coatings
  { id: 208, sku: 'PNT-FL-001', name: 'Epoxy Floor Coating 20kg',          category: 'Paint', subCategory: 'paint-floor',      brand: 'Asian Paints', unit: 'Kg',     purchasePrice: 2800, sellingPrice: 3650, wholesalePrice: 3200, gst: 18, stock: 8,  minStock: 2,  maxStock: 25,  warehouse: 'WH-E', rack: 'R-49', barcode: '8901234580060', status: 'In Stock',  image: '' },
  { id: 209, sku: 'PNT-FL-002', name: 'PU Floor Coating 20kg',             category: 'Paint', subCategory: 'paint-floor',      brand: 'Berger',       unit: 'Kg',     purchasePrice: 3200, sellingPrice: 4150, wholesalePrice: 3650, gst: 18, stock: 6,  minStock: 2,  maxStock: 20,  warehouse: 'WH-E', rack: 'R-49', barcode: '8901234580061', status: 'In Stock',  image: '' },
  { id: 210, sku: 'PNT-FL-003', name: 'Concrete Floor Paint 20L',          category: 'Paint', subCategory: 'paint-floor',      brand: 'Nerolac',      unit: 'Litre',  purchasePrice: 1800, sellingPrice: 2350, wholesalePrice: 2060, gst: 18, stock: 10, minStock: 3,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-49', barcode: '8901234580062', status: 'In Stock',  image: '' },
  { id: 211, sku: 'PNT-FL-004', name: 'Anti-Skid Floor Paint 20L',         category: 'Paint', subCategory: 'paint-floor',      brand: 'Nippon',       unit: 'Litre',  purchasePrice: 2000, sellingPrice: 2600, wholesalePrice: 2300, gst: 18, stock: 8,  minStock: 2,  maxStock: 25,  warehouse: 'WH-E', rack: 'R-49', barcode: '8901234580063', status: 'In Stock',  image: '' },
  { id: 212, sku: 'PNT-FL-005', name: 'Road Marking White 20L',            category: 'Paint', subCategory: 'paint-floor',      brand: 'Asian Paints', unit: 'Litre',  purchasePrice: 1600, sellingPrice: 2100, wholesalePrice: 1840, gst: 18, stock: 10, minStock: 3,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-49', barcode: '8901234580064', status: 'In Stock',  image: '' },
  { id: 213, sku: 'PNT-FL-006', name: 'Road Marking Yellow 20L',           category: 'Paint', subCategory: 'paint-floor',      brand: 'Asian Paints', unit: 'Litre',  purchasePrice: 1600, sellingPrice: 2100, wholesalePrice: 1840, gst: 18, stock: 10, minStock: 3,  maxStock: 30,  warehouse: 'WH-E', rack: 'R-49', barcode: '8901234580065', status: 'In Stock',  image: '' },

  // ── Paint → Thinners & Solvents
  { id: 214, sku: 'PNT-TH-001', name: 'Paint Thinner 1L',                  category: 'Paint', subCategory: 'paint-thinner',    brand: 'Generic',      unit: 'Litre',  purchasePrice: 65,   sellingPrice: 90,   wholesalePrice: 78,   gst: 18, stock: 80, minStock: 20, maxStock: 300, warehouse: 'WH-E', rack: 'R-50', barcode: '8901234580066', status: 'In Stock',  image: '' },
  { id: 215, sku: 'PNT-TH-002', name: 'PU Thinner 1L',                     category: 'Paint', subCategory: 'paint-thinner',    brand: 'Generic',      unit: 'Litre',  purchasePrice: 95,   sellingPrice: 125,  wholesalePrice: 110,  gst: 18, stock: 50, minStock: 12, maxStock: 200, warehouse: 'WH-E', rack: 'R-50', barcode: '8901234580067', status: 'In Stock',  image: '' },
  { id: 216, sku: 'PNT-TH-003', name: 'Turpentine Oil 1L',                 category: 'Paint', subCategory: 'paint-thinner',    brand: 'Generic',      unit: 'Litre',  purchasePrice: 75,   sellingPrice: 100,  wholesalePrice: 88,   gst: 18, stock: 80, minStock: 20, maxStock: 300, warehouse: 'WH-E', rack: 'R-50', barcode: '8901234580068', status: 'In Stock',  image: '' },
  { id: 217, sku: 'PNT-TH-004', name: 'Mineral Turpentine Oil 5L',         category: 'Paint', subCategory: 'paint-thinner',    brand: 'Generic',      unit: 'Litre',  purchasePrice: 320,  sellingPrice: 420,  wholesalePrice: 370,  gst: 18, stock: 30, minStock: 8,  maxStock: 100, warehouse: 'WH-E', rack: 'R-50', barcode: '8901234580069', status: 'In Stock',  image: '' },
  { id: 218, sku: 'PNT-TH-005', name: 'Brush Cleaner 500ml',               category: 'Paint', subCategory: 'paint-thinner',    brand: '3M',           unit: 'Bottle', purchasePrice: 95,   sellingPrice: 125,  wholesalePrice: 110,  gst: 18, stock: 40, minStock: 10, maxStock: 150, warehouse: 'WH-E', rack: 'R-50', barcode: '8901234580070', status: 'In Stock',  image: '' },

  // ── Paint → Hardeners & Additives
  { id: 219, sku: 'PNT-AD-001', name: 'PU Hardener 500ml',                 category: 'Paint', subCategory: 'paint-additive',   brand: 'Berger',       unit: 'Bottle', purchasePrice: 280,  sellingPrice: 370,  wholesalePrice: 325,  gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-51', barcode: '8901234580071', status: 'In Stock',  image: '' },
  { id: 220, sku: 'PNT-AD-002', name: 'Epoxy Hardener 500ml',              category: 'Paint', subCategory: 'paint-additive',   brand: 'Asian Paints', unit: 'Bottle', purchasePrice: 320,  sellingPrice: 420,  wholesalePrice: 370,  gst: 18, stock: 15, minStock: 4,  maxStock: 50,  warehouse: 'WH-E', rack: 'R-51', barcode: '8901234580072', status: 'In Stock',  image: '' },
  { id: 221, sku: 'PNT-AD-003', name: 'Tinting Paste Red 500ml',           category: 'Paint', subCategory: 'paint-additive',   brand: 'Generic',      unit: 'Bottle', purchasePrice: 85,   sellingPrice: 115,  wholesalePrice: 100,  gst: 18, stock: 30, minStock: 8,  maxStock: 100, warehouse: 'WH-E', rack: 'R-51', barcode: '8901234580073', status: 'In Stock',  image: '' },
  { id: 222, sku: 'PNT-AD-004', name: 'Tinting Paste Blue 500ml',          category: 'Paint', subCategory: 'paint-additive',   brand: 'Generic',      unit: 'Bottle', purchasePrice: 85,   sellingPrice: 115,  wholesalePrice: 100,  gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-51', barcode: '8901234580074', status: 'In Stock',  image: '' },
  { id: 223, sku: 'PNT-AD-005', name: 'Tinting Paste Black 500ml',         category: 'Paint', subCategory: 'paint-additive',   brand: 'Generic',      unit: 'Bottle', purchasePrice: 85,   sellingPrice: 115,  wholesalePrice: 100,  gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-51', barcode: '8901234580075', status: 'In Stock',  image: '' },

  // ── Paint → Brushes & Rollers
  { id: 224, sku: 'PNT-BR-001', name: 'Wall Paint Brush 4 inch',           category: 'Paint', subCategory: 'paint-brush',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 35,   sellingPrice: 55,   wholesalePrice: 45,   gst: 18, stock: 80, minStock: 20, maxStock: 300, warehouse: 'WH-E', rack: 'R-52', barcode: '8901234580076', status: 'In Stock',  image: '' },
  { id: 225, sku: 'PNT-BR-002', name: 'Wall Paint Brush 6 inch',           category: 'Paint', subCategory: 'paint-brush',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 55,   sellingPrice: 85,   wholesalePrice: 70,   gst: 18, stock: 60, minStock: 15, maxStock: 200, warehouse: 'WH-E', rack: 'R-52', barcode: '8901234580077', status: 'In Stock',  image: '' },
  { id: 226, sku: 'PNT-BR-003', name: 'Enamel Paint Brush 2 inch',         category: 'Paint', subCategory: 'paint-brush',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 20,   sellingPrice: 32,   wholesalePrice: 26,   gst: 18, stock: 100,minStock: 25, maxStock: 400, warehouse: 'WH-E', rack: 'R-52', barcode: '8901234580078', status: 'In Stock',  image: '' },
  { id: 227, sku: 'PNT-BR-004', name: 'Enamel Paint Brush 1 inch',         category: 'Paint', subCategory: 'paint-brush',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 12,   sellingPrice: 20,   wholesalePrice: 16,   gst: 18, stock: 120,minStock: 30, maxStock: 500, warehouse: 'WH-E', rack: 'R-52', barcode: '8901234580079', status: 'In Stock',  image: '' },
  { id: 228, sku: 'PNT-BR-005', name: 'Foam Roller 9 inch',                category: 'Paint', subCategory: 'paint-brush',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 45,   sellingPrice: 70,   wholesalePrice: 58,   gst: 18, stock: 60, minStock: 15, maxStock: 200, warehouse: 'WH-E', rack: 'R-52', barcode: '8901234580080', status: 'In Stock',  image: '' },
  { id: 229, sku: 'PNT-BR-006', name: 'Microfiber Roller 9 inch',          category: 'Paint', subCategory: 'paint-brush',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 65,   sellingPrice: 100,  wholesalePrice: 85,   gst: 18, stock: 40, minStock: 10, maxStock: 150, warehouse: 'WH-E', rack: 'R-52', barcode: '8901234580081', status: 'In Stock',  image: '' },
  { id: 230, sku: 'PNT-BR-007', name: 'Texture Roller 9 inch',             category: 'Paint', subCategory: 'paint-brush',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 85,   sellingPrice: 130,  wholesalePrice: 110,  gst: 18, stock: 25, minStock: 6,  maxStock: 80,  warehouse: 'WH-E', rack: 'R-52', barcode: '8901234580082', status: 'In Stock',  image: '' },

  // ── Paint → Painting Tools & Accessories
  { id: 231, sku: 'PNT-TL-001', name: 'Paint Tray 9 inch',                 category: 'Paint', subCategory: 'paint-tools',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 45,   sellingPrice: 70,   wholesalePrice: 58,   gst: 18, stock: 50, minStock: 12, maxStock: 200, warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580083', status: 'In Stock',  image: '' },
  { id: 232, sku: 'PNT-TL-002', name: 'Putty Knife 4 inch',                category: 'Paint', subCategory: 'paint-tools',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 35,   sellingPrice: 55,   wholesalePrice: 45,   gst: 18, stock: 60, minStock: 15, maxStock: 200, warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580084', status: 'In Stock',  image: '' },
  { id: 233, sku: 'PNT-TL-003', name: 'Paint Scraper',                     category: 'Paint', subCategory: 'paint-tools',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 25,   sellingPrice: 40,   wholesalePrice: 33,   gst: 18, stock: 60, minStock: 15, maxStock: 200, warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580085', status: 'In Stock',  image: '' },
  { id: 234, sku: 'PNT-TL-004', name: 'Masking Tape 1 inch',               category: 'Paint', subCategory: 'paint-tools',      brand: '3M',           unit: 'Roll',   purchasePrice: 28,   sellingPrice: 45,   wholesalePrice: 38,   gst: 18, stock: 100,minStock: 25, maxStock: 400, warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580086', status: 'In Stock',  image: '' },
  { id: 235, sku: 'PNT-TL-005', name: "Painter's Tape 2 inch",             category: 'Paint', subCategory: 'paint-tools',      brand: '3M',           unit: 'Roll',   purchasePrice: 45,   sellingPrice: 70,   wholesalePrice: 58,   gst: 18, stock: 80, minStock: 20, maxStock: 300, warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580087', status: 'In Stock',  image: '' },
  { id: 236, sku: 'PNT-TL-006', name: 'Sandpaper 120 Grit (per sheet)',    category: 'Paint', subCategory: 'paint-tools',      brand: 'Generic',      unit: 'Sheet',  purchasePrice: 8,    sellingPrice: 14,   wholesalePrice: 11,   gst: 18, stock: 200,minStock: 50, maxStock: 1000,warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580088', status: 'In Stock',  image: '' },
  { id: 237, sku: 'PNT-TL-007', name: 'Sandpaper 80 Grit (per sheet)',     category: 'Paint', subCategory: 'paint-tools',      brand: 'Generic',      unit: 'Sheet',  purchasePrice: 8,    sellingPrice: 14,   wholesalePrice: 11,   gst: 18, stock: 150,minStock: 40, maxStock: 800, warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580089', status: 'In Stock',  image: '' },
  { id: 238, sku: 'PNT-TL-008', name: 'Silicone Sealant 280ml',            category: 'Paint', subCategory: 'paint-tools',      brand: 'Fevicol',      unit: 'Tube',   purchasePrice: 95,   sellingPrice: 130,  wholesalePrice: 115,  gst: 18, stock: 60, minStock: 15, maxStock: 200, warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580090', status: 'In Stock',  image: '' },
  { id: 239, sku: 'PNT-TL-009', name: 'Acrylic Sealant 280ml',             category: 'Paint', subCategory: 'paint-tools',      brand: '3M',           unit: 'Tube',   purchasePrice: 85,   sellingPrice: 115,  wholesalePrice: 100,  gst: 18, stock: 50, minStock: 12, maxStock: 150, warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580091', status: 'In Stock',  image: '' },
  { id: 240, sku: 'PNT-TL-010', name: 'Extension Rod 18 inch',             category: 'Paint', subCategory: 'paint-tools',      brand: 'Generic',      unit: 'Piece',  purchasePrice: 120,  sellingPrice: 180,  wholesalePrice: 155,  gst: 18, stock: 20, minStock: 5,  maxStock: 60,  warehouse: 'WH-E', rack: 'R-53', barcode: '8901234580092', status: 'In Stock',  image: '' },

 ];

export const INVENTORY_STATS = [
  { label: 'Total Products', value: '20', icon: 'inventory_2', color: '#2563eb' },
  { label: 'Low Stock',      value: '18', icon: 'warning',     color: '#f59e0b' },
  { label: 'Out of Stock',   value: '0',  icon: 'block',       color: '#dc2626' },
  { label: 'Total Value',    value: '₹2,84,650', icon: 'payments', color: '#16a34a' },
];
